name: 'Install build dependencies'
description: 'Install gfortran, LAPACK, BLAS, SCALAPACK, OpenMPI, Python packages, and runtime test dependencies'

runs:
  using: 'composite'
  steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gfortran liblapack-dev libblas-dev \
            libopenmpi-dev openmpi-bin libscalapack-mpi-dev \
            python3 python3-numpy python3-scipy \
            time bc \
            libhdf5-dev hdf5-tools
      shell: bash
