name: 'Install build dependencies'
description: 'Install gfortran, LAPACK, BLAS, SCALAPACK, OpenMPI, and Python packages'

runs:
  using: 'composite'
  steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gfortran liblapack-dev libblas-dev \
            libopenmpi-dev openmpi-bin libscalapack-mpi-dev \
            python3 python3-numpy python3-scipy
      shell: bash
