#-------------------------------------------------------------------------------
# CI/CD deployment for Tantalus on ULB GITLAB
#-------------------------------------------------------------------------------
image: ubuntu # Only needed when running on systems that use docker

stages:
 - compilation # Test whether the code compiles with gfortran
 - testing     # All types of numerical testing

compile:
  #----------------------------------------------------------------------------
  # Perform several different compilations for .exe's
  #----------------------------------------------------------------------------
  stage: compilation
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
  variables:
    EXENAME: Tantalus.${CONFIG}.${COMPILER}.${CALCTYPE}.exe
  tags:
    - astropc19
  artifacts:
    paths:
      - exec/${EXENAME}
    expire_in: 2 days # Don't keep the exe's around for long
  parallel:
    matrix:
      - CONFIG  : [NLO,BXL,BXL-P,BXL-T,BXL-TP,N2LO,N2LO-P,N2LO-T,N2LO-TP]
        COMPILER: gnu
        CALCTYPE: NUCLEI
      - CONFIG  : BXL
        COMPILER: intel
        CALCTYPE: PASTA
      - CONFIG  : [NLO,BXL]
        COMPILER: intel
        CALCTYPE: NUCLEI
  script:
    #---------------------------------------------------------------------------
    # This is a horrible hack:
    #   unfortunately the current Makefile configuration of Tantalus will always
    #   fail the first time around because Hephaestos has not created f90 files
    #   in the src/ directory yet. I have not found a way to correctly do this
    #   dependency in the Makefile yet...;
    #---------------------------------------------------------------------------
    - mkdir src/
    - cp src_orig/*.f90 src
    # Copy the compilation settings to make.inc
    - cp make_include/make.inc.${COMPILER}-serial make.inc
    #---------------------------------------------------------------------------
    # Make sure that the intel compilers and libraries are available
    - source /opt/intel/oneapi/setvars.sh --force &> /dev/null
    #---------------------------------------------------------------------------
    # Compiles the selected configuration file with the selected compiler,
    #    resulting in a specific executable
    - make CONFIG=${CONFIG} COMPILER=${COMPILER} EXENAME=${EXENAME} CALCTYPE=${CALCTYPE}

minimal:
  #-----------------------------------------------------------------------------
  # Run the 'minimal' test for two different compilers.
  #-----------------------------------------------------------------------------
  stage: testing
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    when: always
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    when: manual
  tags:
    - astropc19
  variables:
    SUFFIX: NLO.${COMPILER}.NUCLEI
  artifacts:
    paths:
      - testing/integration/logs/minimal.${SUFFIX}.out
    expire_in: 1 year # keep outputs for a LONG time
  parallel:
    matrix:
      - COMPILER: [gnu, intel]
  script:
    #---------------------------------------------------------------------------
    # Make sure that the intel compilers and libraries are available
    - source /opt/intel/oneapi/setvars.sh --force &> /dev/null
    #---------------------------------------------------------------------------
    # Start testing!
    - cd testing/integration/
    - bash minimal.sh $SUFFIX # Spherical O16 with SLy4

symmetries:
  #-----------------------------------------------------------------------------
  # Run the 'symmetries' test
  # Currently implemented runs:
  #  - BSkG3  with the BXL  configuration compiled with gfortran
  #  - SN2LO1 with the N2LO configuration compiled with gfortran
  #-----------------------------------------------------------------------------
  stage: testing
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
  tags:
    - astropc19
  variables:
    EXEC    : ${CONFIG}.${COMPILER}.${CALCTYPE}
    EXEC_P  : ${CONFIG}-P.${COMPILER}.${CALCTYPE}
    EXEC_T  : ${CONFIG}-T.${COMPILER}.${CALCTYPE}
    EXEC_TP : ${CONFIG}-TP.${COMPILER}.${CALCTYPE}
  artifacts:
    paths:
      - testing/integration/logs/symmetries.${EXEC}.out
      - testing/integration/logs/symmetries.${EXEC_P}.out
      - testing/integration/logs/symmetries.${EXEC_T}.out
      - testing/integration/logs/symmetries.${EXEC_TP}.out
    expire_in: 1 year # keep outputs for a LONG time
  parallel:
    matrix:
      - PARAM    : BSkG3
        CONFIG   : BXL
        COMPILER : gnu
        CALCTYPE : NUCLEI
      - PARAM    : SN2LO1
        CONFIG   : N2LO
        COMPILER : gnu
        CALCTYPE : NUCLEI
  script:
    #---------------------------------------------------------------------------
    # Start testing!
    - cd testing/integration/
    # Useage: bash symmetries param exec exec_P exec_T exec_TP
    - bash symmetries.sh ${PARAM} ${EXEC} ${EXEC_P} ${EXEC_T} ${EXEC_TP}

store_derivatives:
  #-----------------------------------------------------------------------------
  # Run the 'store_derivatives' test
  # Currently implemented runs:
  #  - BSkG3   with the BXL    configuration compiled with gfortran
  #  - BSkG3   with the BXL-P  configuration compiled with gfortran
  #  - BSkG3   with the BXL-T  configuration compiled with gfortran
  #  - S2NLO1  with the N2LO   configuration compiled with gfortran
  #  - S2NLO1  with the N2LO-P configuration compiled with gfortran
  #  - S2NLO1  with the N2LO-T configuration compiled with gfortran
  #-----------------------------------------------------------------------------
  stage: testing
  tags:
    - astropc19
  variables:
    EXEC    : ${CONFIG}.${COMPILER}.${CALCTYPE}
  artifacts:
    paths:
      - testing/integration/logs/store_derivatives=.true..${EXEC}.out
      - testing/integration/logs/store_derivatives=.false..${EXEC}.out
    expire_in: 1 year # keep outputs for a LONG time
  parallel:
    matrix:
      - PARAM    : BSkG3
        CONFIG   : [BXL, BXL-T, BXL-P]
        COMPILER : gnu
        CALCTYPE : NUCLEI
      - PARAM    : SN2LO1
        CONFIG   : [N2LO, N2LO-T, N2LO-P]
        COMPILER : gnu
        CALCTYPE : NUCLEI
  script:
    #---------------------------------------------------------------------------
    # Start testing!
    - cd testing/integration/
    # Useage: bash symmetries param exec exec_P exec_T exec_TP
    - bash store_derivatives.sh -p ${PARAM} -e ${EXEC}

  #----------------------------------------------------------------------
  # Install all prerequisites for docker-based systems
  #   I'm keeping this around for future configurations
  #----------------------------------------------------------------------
  # Note: the -y serves to skip all prompts
  #- apt update
  #- apt install make -y                          # to use the Makefile
  #- apt-get install gfortran -y                  # to compile
  #- apt-get install libblas-dev liblapack-dev -y # LAPACK library
  #- apt-get install python3  -y                  # to run Hephaestos
  #- apt-get install python3-numpy    -y
  #- apt-get install python3-scipy    -y
  #- apt-get install git              -y          # for setting version info
