import matplotlib.pyplot as plt
import networkx as nx
import pydot
from networkx.drawing.nx_pydot import graphviz_layout

G = nx.DiGraph()

G.add_edges_from(
    [ ('basis_transform', 'geninfo')
    , ('basis_transform', 'wavefunctions')
    , ('basis_transform', 'timing')
    , ('BCS','vectors')
    , ('BCS','wavefunctions')
    , ('BCS', 'pairingcutoffs')
    , ('constants', 'compilation')
    , ('convergence', 'geninfo')
    , ('Coulombmod', 'geninfo')
    , ('Coulombmod', 'densities')
    , ('Coulombmod', 'parameterization')
    , ('Coulombmod', 'timing')
    , ('cranking', 'compilation')
    , ('cranking', 'geninfo')
    , ('cranking', 'derivatives')
    , ('cranking', 'wavefunctions')
    , ('cranking', 'nil8')
    , ('cranking', 'pairing')
    , ('cranking', 'densities')
    , ('densities', 'compilation')
    , ('densities', 'geninfo')
    , ('densities', 'vectors')
    , ('densities', 'wavefunctions')
    , ('densities', 'pairing')
    , ('densities', 'derivatives')
    , ('densities', 'preconditioning')
    , ('densities', 'timing')
    , ('derivatives', 'geninfo')
    , ('evolution', 'wavefunctions')
    , ('evolution', 'functional')
    , ('evolution', 'preconditioning')
    , ('evolution', 'timing')
    , ('fam', 'densities')
    , ('fam', 'moments')
    , ('fam', 'fission_MOI')
    , ('fam', 'evolution')
    , ('gmres', 'geninfo')
    , ('fam_testing', 'densities')
    , ('fam_testing', 'moments')
    , ('fam_testing', 'Coulombmod')
    , ('fam_testing', 'pairing')
    , ('fam_testing', 'fission_MOI')
    , ('fam_testing', 'functional')
    , ('fam_testing', 'evolution')
    , ('fam_testing', 'fam')
    , ('fam_testing', 'gmres')
    , ('fission_MOI', 'geninfo')
    , ('fission_MOI', 'densities')
    , ('fission_MOI', 'parameterization')
    , ('fission_MOI', 'moments')
    , ('fission_MOI', 'timing')
    , ('folding', 'geninfo')
    , ('functional', 'compilation')
    , ('functional', 'geninfo')
    , ('functional', 'densities')
    , ('functional', 'parameterization')
    , ('functional', 'pairing')
    , ('functional', 'transform')
    , ('functional', 'vectors')
    , ('functional', 'cranking')
    , ('functional', 'pairing_strengths')
    , ('functional', 'timing')
    , ('functional', 'HDF5')
    , ('geninfo', 'compilation')
    , ('geninfo', 'MPI')
    , ('hartreefock', 'MPI')
    , ('hartreefock', 'wavefunctions')
    , ('HFB', 'geninfo')
    , ('HFB', 'vectors')
    , ('HFB', 'wavefunctions')
    , ('HFB', 'pairingcutoffs')
    , ('HFB', 'HFB_direct')
    , ('HFB', 'HFB_gradient')
    , ('HFB_direct', 'wavefunctions')
    , ('HFB_direct', 'parameterization')
    , ('HFB_gradient', 'wavefunctions')
    , ('IO', 'geninfo')
    , ('IO', 'wavefunctions')
    , ('IO', 'pairing')
    , ('IO', 'functional')
    , ('IO', 'momentsofinertie')
    , ('IO', 'moments')
    , ('IO', 'Coulombmod')
    , ('IO', 'transform')
    , ('IO', 'fission_MOI')
    , ('IO', 'IO_wf')
    , ('IO', 'HDF5')
    , ('IO_wf', 'compilation')
    , ('IO_wf', 'geninfo')
    , ('IO_wf', 'wavefunctions')
    , ('IO_wf', 'functional')
    , ('IO_wf', 'transform')
    , ('moments', 'geninfo')
    , ('moments', 'sphericalharmonics')
    , ('moments', 'densities')
    , ('momentsofinertia', 'geninfo')
    , ('momentsofinertia', 'densities')
    , ('momentsofinertia', 'parameterization')
    , ('nil8', 'compilation')
    , ('pairing', 'compilation')
    , ('pairing', 'geninfo')
    , ('pairing', 'wavefunctions')
    , ('pairing', 'functional')
    , ('pairing', 'BCS')
    , ('pairing', 'HFB')
    , ('pairing', 'HFB_gradient')
    , ('pairing', 'pairingcutoffs')
    , ('pairing', 'parameterization')
    , ('pairing', 'pairing_strengths')
    , ('pairing', 'timing')
    , ('pairing', 'MPI')
    , ('pairing_strengths', 'geninfo')
    , ('pairing_strengths', 'MPI')
    , ('pairingcutoffs', 'wavefunctions')
    , ('parameterization', 'iso_fortran_env')
    , ('parameterization', 'pairingcutoffs')
    , ('preconditioning', 'derivatives')
    , ('printing', 'geninfo')
    , ('printing', 'pairing')
    , ('printing', 'wavefunctions')
    , ('printing', 'convergence')
    , ('scfiteration', 'functional')
    , ('scfiteration', 'geninfo')
    , ('sphericalharmonics', 'geninfo')
    , ('Tantalus', 'geninfo')
    , ('timing', 'compilation')
    , ('timing', 'geninfo')
    , ('timing', 'iso_fortran_env')
    , ('timing', 'MPI')
    , ('timing', 'densities')
    , ('transform', 'geninfo')
    , ('transform', 'wavefunctions')
    , ('transform', 'pairing')
    , ('vectors', 'geninfo')
    , ('version', 'geninfo')
    , ('version', 'IO')
    , ('wavefunctions', 'derivatives')
    , ('wavefunctions', 'nil8')
    , ('wavefunctions', 'MPI')
    ]
)

pos = graphviz_layout(G, prog="dot")
for k,v in pos.items():
    pos[k]=(-v[1],v[0])

nx.draw_networkx_nodes(G,pos = pos, node_shape = 's', node_size = 200,
                       node_color = 'none', edgecolors='k')
nx.draw_networkx_edges(G,pos = pos,
                       node_shape = 's', width = 1,  node_size = 200)
nx.draw_networkx_labels(G,pos = pos, font_size = 5)

plt.show()
