#-------------------------------------------------------------------------------
# Module that makes sure all of the FORTRAN generated by Hephaestos actually  
# fits within the character limits.
#-------------------------------------------------------------------------------
import textwrap

def LineFormat_oneline(code):
    # Takes as input a line of fortran code, and outputs the same line 
    # split over multiple lines if necessary for the character limit.

    if(len(code) <= 100):
        splitcode = code
    else:
        split = textwrap.wrap(code, width=100, break_long_words=False)
        splitcode = ''
        for c in split:
            splitcode = splitcode + ' & ' + c + '& \n'
        
        splitcode = splitcode[2:-3]
    return(splitcode)

def LineFormat(code):
    # Remove trailing whitespace
    code = code.rstrip()
    split = code.split('\n')

    splitcode= ''  
    for l in split:
        splitcode = splitcode + LineFormat_oneline(l) + '\n'
    return splitcode
