module functional
 !==============================================================================
 !_________ _______  _       _________ _______  _                 _______ 
 !\__   __/(  ___  )( (    /|\__   __/(  ___  )( \      |\     /|(  ____ \
 !   ) (   | (   ) ||  \  ( |   ) (   | (   ) || (      | )   ( || (    \/
 !   | |   | (___) ||   \ | |   | |   | (___) || |      | |   | || (_____ 
 !   | |   |  ___  || (\ \) |   | |   |  ___  || |      | |   | |(_____  )
 !   | |   | (   ) || | \   |   | |   | (   ) || |      | |   | |      ) |
 !   | |   | )   ( || )  \  |   | |   | )   ( || (____/\| (___) |/\____) |
 !   )_(   |/     \||/    )_)   )_(   |/     \|(_______/(_______)\_______)
 !                                                                       
 !  Copyright W. Ryssens & M. Bender
 !
 !==============================================================================
 !
 ! Module containing the means to calculate (and print) the mean-field energy.
 ! Note that the actual coupling constants are contained in the constants.f90
 ! file. 
 !==============================================================================
 
 use compilation
 use geninfo
 use densities
 use parameterization

 implicit none
 
    !===========================================================================
    ! PARAMETERIZATION DEFINITION OPTIONS
    !===========================================================================
    !---------------------------------------------------------------------------
    ! Name of the parameterization
    character(len=20) :: name_param 
    ! Name of the functional file this code was compiled with
    character(len=20), parameter :: func_name = $FUNC_NAME
!    !---------------------------------------------------------------------------
!    ! List of coupling constants that can be employed by .func files to 
!    ! define a functional.
!    !---------------------------------------------------------------------------
!    real(KIND=dp) :: t0=-2488.913
!    real(KIND=dp) :: x0=0.834
!    real(KIND=dp) :: t1=486.818
!    real(KIND=dp) :: x1=-0.344
!    real(KIND=dp) :: t2=-546.395
!    real(KIND=dp) :: x2=-1.0
!    real(KIND=dp) :: t3=13777.0
!    real(KIND=dp) :: x3=1.354
!    real(KIND=dp) :: yt3a= 0.166666666666666666667 
!    real(KIND=dp) :: te=0.0
!    real(KIND=dp) :: to=0.0
!    real(KIND=dp) :: wso=123.0
!    real(KIND=dp) :: wsoq=123.0
!    !---------------------------------------------------------------------------
!    ! N2LO Central
!    real(KIND=dp) :: t1n2=24.3409
!    real(KIND=dp) :: t2n2=-27.31975
!    real(KIND=dp) :: x1n2=-0.344
!    real(KIND=dp) :: x2n2=-1.0  
!    !---------------------------------------------------------------------------
!    ! N3LO central
!    real(KIND=dp) :: t1n3= 2.3409
!    real(KIND=dp) :: t2n3=-2.31975
!    real(KIND=dp) :: x1n3=-0.344
!    real(KIND=dp) :: x2n3=-1.0 
!    !---------------------------------------------------------------------------
!    ! N2LO Tensor
!    ! Note that these are the constants from Michaels notes, that is to say 
!    ! 4 times as large as the ones in Danys/Lysandras notes
!    real(KIND=dp) :: ten2 =  40.0
!    real(KIND=dp) :: ton2 = -20.0  

    !---------------------------------------------------------------------------
    ! Definition of global contributions to the energy
    real(KIND=dp) :: Kinetic(2), Skyrme(2), TotalE, SpwfEnergy
    real(KIND=dp) :: COMCorrection(2,2), CoulombDirect, CoulombExchange
    !===========================================================================
    ! NUMERICAL OPTIONS
    !===========================================================================
    !---------------------------------------------------------------------------
    ! Small non-zero value that can be used in a .func file to safeguard against
    ! division by zero. 
    real(KIND=dp) :: eps =1d-20
    !---------------------------------------------------------------------------
    ! Factor in the preconditioning of the F_I_I potential
    real(KIND=dp) :: preconfactor = 1.0_dp
    !---------------------------------------------------------------------------
    ! Type of preconditioning to apply
    integer       :: potentialpreconditioning = 1
    !===========================================================================
    ! AUTOMATICALLY GENERATED DECLARATIONS
    !===========================================================================
    !---------------------------------------------------------------------------
    ! Declaration of
    ! a) Coupling constants
    ! b) Terms in the energy
    ! c) Fields
    ! d) Previous_values of the fields
    ! All automatically generated by Hephaestos
    !---------------------------------------------------------------------------
$DECLARATION
    !---------------------------------------------------------------------------
      
contains

 subroutine readfunctional()
    !---------------------------------------------------------------------------
    ! Initializes the functional
    ! a) read the details of the parameterization from file
    ! b) calculate the coupling constants
    !---------------------------------------------------------------------------
    
    namelist /func/ name_param
    
    read(unit=*, nml=func) 
   
    name_param = to_upper(name_param)
    
    call readparameterization(name_param, func_name)
    call calcedfcoefs()

 end subroutine readfunctional
 
 subroutine calcedfcoefs()
     !--------------------------------------------------------------------------
     ! Calculate the coupling constants from the expressions passed into 
     ! Hephaestos.
     !
     !--------------------------------------------------------------------------
$CALCCOEF
    
    nucleonmass = 0.5*(nucleonmass(1) + nucleonmass(2))
 
 end subroutine calcedfcoefs
 
 subroutine printedfcoefs
    !---------------------------------------------------------------------------
    ! Print the values of the EFD coefs used.
    !---------------------------------------------------------------------------
    1 format (90('-'))
    2 format (' Skyrme coupling constants ')
    3 format (26x, 'Isospin representation BFH representation')
    4 format (26x, 'scalar      vector      total       (n-p)')
    
    print 1
    print 2
    print 3
    print 4
    print 1
    ! This part is automatically generated by Hephaestos.
$PRINTCOEF    
    print 1
 end subroutine printedfcoefs

 subroutine PrintEnergy()
    1 format (90('-'))
    5 format (30x, '      neutron        proton         total')
    6 format (15x, 'Kinetic Energy:', 3f15.6)
   61 format (15x, '    COM 1-body:', 3f15.6)
    7 format (15x, 'Coulomb Direct:', 3f15.6)
    8 format (15x, '      Exchange:', 3f15.6)
    
    9 format (15x, '  Total energy:', 30x, f15.6)
   10 format (15x, '    from spwfs:', 30x, f15.6)

    call printSkyrme

    print 1
    print 5
    print 6, Kinetic, sum(Kinetic)
    print 61, COMcorrection(1,:), sum(COMcorrection(1,:))
    print 7, 0.0, CoulombDirect, CoulombDirect
    print 8, 0.0, CoulombExchange, CoulombExchange
    print 1
    print  9, TotalE
    print 10, spwfenergy
    print 1
 end subroutine PrintEnergy
 
 subroutine CalcEnergy
    !---------------------------------------------------------------------------
    ! Calculate all of the relevant energies.
    !---------------------------------------------------------------------------
    
    use Coulombmod, only : CoulombEnergy_Direct,CoulombEnergy_Exchange
    
    ! Kinetic energy
    Kinetic = CompKinetic()
    ! COM correction
    call CompCOMCorrection()
    ! Skyrme functional
    call compSkyrme()

    ! Direct contribution of the Coulomb potential
    CoulombDirect   = CoulombEnergy_Direct(D_I_I(:,2))
    ! Exchange contribution
    CoulombExchange = CoulombEnergy_Exchange(D_I_I(:,2)) 

    ! Total energy
    TotalE = sum(Skyrme + Kinetic) + sum(COMCorrection)
    TotalE = TotalE + CoulombDirect + CoulombExchange

    ! Total energy from single-particle energies
    SpwfEnergy = calcspwfenergy()

 end subroutine CalcEnergy
 
 subroutine CompSkyrme()
    !---------------------------------------------------------------------------
    ! Calculate the Skyrme part to the functional.
    !---------------------------------------------------------------------------
    real(KIND=dp) :: Edensity(mv,3)
    integer       :: m
    
$CALCULATION
    
    Skyrme = &
$TOTAL

 end subroutine CompSkyrme
 
 subroutine PrintSkyrme()
    !---------------------------------------------------------------------------
    ! Print all contributions to the energy.
    !
    !---------------------------------------------------------------------------
    
    1 format (90('-'))
    2 format (' Skyrme Energy ')
    3 format (35x, 'isoscalar      isovector      total')
    4 format (17x, 'Total Skyrme:', 3f15.6)
    
    print 1
    print 2
    print 3
    print 1
    
$PRINT 

    print 1
    print 4, Skyrme, sum(Skyrme)
    print 1
 end subroutine PrintSkyrme

 function CompKinetic() result(kinetic)
    !---------------------------------------------------------------------------
    ! This subroutine computes the total kinetic energy,
    ! according to the following formula:
    !    E_k = -\hbar/2m \int d^3x \sum_{k} v_{k} \Psi_k^* \Delta \Psi_k
    !---------------------------------------------------------------------------
    ! Note that the 1-body c.o.m. correction is not taken into account here!
    !---------------------------------------------------------------------------
    use Constants

    integer          :: wave, it,k,i
    real(KIND=dp)    :: Inproduct
    real(KIND=dp)    :: Kinetic(2)

    ! Kinetic Energy
    Kinetic = 0.0_dp
    do wave=1,nwt
        ! Isospin is neutron in the first half of blocks, proton in the rest
        it = 2
        if(wave.le.sum(HFBlocks(1:Blocks/2))) it = 1

        Inproduct = 0.0_dp
        do k=1,4          
                do i=1,mv
                       Inproduct = Inproduct + HFPsi(i,k,wave) *  & 
                       &  ( HFddPsi(i,1,k,wave) + &
                       &    HFddPsi(i,4,k,wave) + &
                       &    HFddPsi(i,6,k,wave))
                enddo
        enddo
        Kinetic(it)= Kinetic(it) + Occupations(wave)*Inproduct
    enddo
    Kinetic=-Kinetic * hbm * dv
    return
  end function CompKinetic
  
  subroutine CompCOMCorrection()
    !---------------------------------------------------------------------------
    ! M. Bender et al., Eur. Phys. J. A 7, 467-478 (2000)
    !---------------------------------------------------------------------------
   
    COMCorrection = 0.0_dp
    if(COM1Body .gt. 0) then
      !Deduce 1-body COM correction from the Kinetic Energy
      COMCorrection(1,:) = - Kinetic(:) * nucleonmass/ &
      &                 (neutrons * nucleonmass(1) + protons * nucleonmass(2))
    endif

  end subroutine CompCOMCorrection

  subroutine calcFields()
    !---------------------------------------------------------------------------
    ! Calculate all of the Skyrme potentials.
    !- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ! Includes preconditioning of F_I_I at the moment only.
    !---------------------------------------------------------------------------
    use Coulombmod , only : SolveCoulomb, CoulombPotential, Exchangepotential
    use moments
    
    integer :: it,i,j,k
    real(KIND=dp), allocatable :: update(:,:)

$CALCFIELDS

    !---------------------------------------------------------------------------
    ! Solve for the Coulomb Potential
    call SolveCoulomb(D_I_I(:,2))
    
    !---------------------------------------------------------------------------
    ! Add the Coulomb contribution to the field corresponding to rho.
    do k=1,nz
      do j=1,ny
        do i=1,nx
          ! Direct contribution
          ! The index juggling is ugly, but necessary. The Coulomb potential
          ! is defined on a slightly larger box using boundary conditions.
          ! A simple abstract statement might mess this up.
          F_I_I(i+(j-1)*nx+(k-1)*ny*nx,2) =                                &
          &       F_I_I(i+(j-1)*nx+(k-1)*ny*nx,2) + CoulombPotential(i,j,k)
        enddo
      enddo
    enddo
    ! Exchange contribution
    F_I_I(1:mv,2) = F_I_I(1:mv,2) + ExchangePotential(1:mv)
    
    !---------------------------------------------------------------------------
    ! Add the contribution from the constraints on the electric multipole 
    ! moments. 
    F_I_I =  F_I_I + Constraint_I_I
    !---------------------------------------------------------------------------
    ! Precondition the field corresponding to rho, F_I_I.
    if(.not.all(F_I_I_hist.eq.0.0_dp) .and. potentialpreconditioning.eq.1) then
      if(.not.allocated(update)) allocate(update(nx*ny*nz,2))
    
      update=  F_I_I - F_I_I_hist
      update=  PreconditionPotential(update,-preconfactor,1.0_dp,+1,+1,+1)
      F_I_I =  F_I_I_hist + update
    endif
        
  end subroutine calcFields 
  
  function sphamil(psi, dpsi, ddpsi, dddpsi, sx,sy,sz,iso, onthefly) &
                                                                  & result(hpsi)
    !---------------------------------------------------------------------------
    ! Apply the action of the single-particle hamiltonian to the 
    ! single-particle wave-functions.
    !---------------------------------------------------------------------------
    
    use derivatives
    
    ! Logical indicating if the derivatives need to be calculated before
    ! applying h.
    ! If false, the derivatives are passed in. If True, the derivatives are not
    ! passed in and need to be calculated.
    logical, intent(in)       :: onthefly 
    
    real(KIND=dp), intent(in)    :: psi(mv,4)  
    real(KIND=dp), intent(inout) :: dpsi(mv,3,4),ddpsi(mv,6,4), dddpsi(mv,10,4)
    integer, intent(in)       :: sx(4),sy(4),sz(4),   iso
    real(KIND=dp)             :: hpsi(mv,4)
    real(KIND=dp)             :: temp(mv,4)
    real(KIND=dp)             ::   dtemp(mv,3,4)
    real(KIND=dp)             ::  ddtemp(mv,3,3,4)
    real(KIND=dp)             :: dddtemp(mv,3,3,3,4)
    real(KIND=dp)             :: laptemp(mv,4)
    
    real(KIND=dp)             :: ReducedMass
    
    integer :: it, i,k
    
    !---------------------------------------------------------------------------
    ! Determine the isospin index
    it = (iso + 3)/2
    !---------------------------------------------------------------------------
    ! Reduced mass in case of self-consistent 1-body COM correction
    if(COM1body .eq. 2) then
        Reducedmass = (1.0_dp-nucleonmass(it)/                                 &
        &                      (neutrons*nucleonmass(1)+protons*nucleonmass(2)))
    else
        Reducedmass = 1.0_dp
    endif
    
    if(OnTheFly) then
      ! Calculate the derivatives
      do k=1,4
!-------------------------------------------------------------------------------
$N2        call Derive_tot(psi(:,k),sx(k),sy(k),sz(k),dpsi(:,:,k),ddpsi(:,:,k))
$N3        call Derive_tot(psi(:,k),sx(k),sy(k),sz(k),dpsi(:,:,k),ddpsi(:,:,k),&
$N3        &                                     dddpsi(:,:,k))
!-------------------------------------------------------------------------------
        enddo
    endif
    !---------------------------------------------------------------------------
    ! Action of the kinetic energy
    do k=1,4
        do i=1,mv
            hpsi(i,k) = - hbm(it)* reducedmass *       (ddpsi(i,1,k) &
            &                                         + ddpsi(i,4,k) &
            &                                         + ddpsi(i,6,k)) 
        enddo
    enddo
    !---------------------------------------------------------------------------
    ! Action of the Skyrme fields
    !
    ! Note that 
    ! a) Coulomb is included in the F_I_I field
    ! b) Every density contains the contributions from constraints on that 
    !    density. 
    ! c) The kinetic energy is NOT included in the F_N_N field, because 
    !    a constant is not in the Lagrange basis; so the current way of
    !    deriving stuff is not correct for a term of the form
    !          hbar^2_2m
    !---------------------------------------------------------------------------
$SKYRMEACTION
    
  end function sphamil
  
  function calcspwfenergy() result(spwfenergy)
    !---------------------------------------------------------------------------
    ! Calculates the total energy from the single-particle energies. 
    !
    !---------------------------------------------------------------------------
    
    use wavefunctions
    use moments
    
    integer       :: wave
    real(KIND=dp) :: spwfenergy, e_rear
    
    ! Start by summing the single-particle energies
    spwfenergy = 0 ; e_rear = 0
    do wave=1,nwt
        spwfenergy = spwfenergy + occupations(wave) * spenergies(wave)
    enddo
    
    ! Calculation of rearrangement energy (without Coulomb Exchange)
$EREAR   

    ! Add the rearrangement energy 
    spwfenergy = spwfenergy - e_rear 
    
    ! Add everything and don't forget about Coulomb exchange
    spwfenergy = 0.5 * spwfenergy + 0.5 * sum(kinetic) + CoulombExchange/3.d0
    
    ! Always add the 1-body COMcorrection. In case it is used iteratively, it
    ! is double counted along with the kinetic energy!
    if(COM1body.gt.0) then
        SpwfEnergy = SpwfEnergy  + sum(COMCorrection(1,:))/2.0_dp
    endif
    
    !Subtract contribution by constraints
    SpwfEnergy = SpwfEnergy - sum(Constraint_I_I * D_I_I)*dv/2.0_dp
    
  end function calcspwfenergy
  
  subroutine output_Edensity(Edensity, N)
    !---------------------------------------------------------------------------
    ! Write the energydensity to a file with name N.
    !
    !
    !---------------------------------------------------------------------------
    character(len=*), intent(in)   :: N
    real(KIND=dp), intent(in), target ::  Edensity(nx*ny*nz,3)
    real(KIND=dp), pointer :: w(:,:,:,:)
    
    real(KIND=dp) :: r,x
    integer       :: i
    
    w(1:nx,1:ny,1:nz,1:3) => Edensity
    
    open(12, File=N)
    
    do i=1,nx
      x = dx/2 + (i-1)*dx
      r = sqrt(3*x**2)
      write(12, '(5f10.5)') r, w(i,i,i,1),  w(i,i,i,2),  w(i,i,i,3) 
    enddo
    close(12)
  end subroutine output_Edensity
end module functional
