module functional
 !==============================================================================
 !_________ _______  _       _________ _______  _                 _______ 
 !\__   __/(  ___  )( (    /|\__   __/(  ___  )( \      |\     /|(  ____ \
 !   ) (   | (   ) ||  \  ( |   ) (   | (   ) || (      | )   ( || (    \/
 !   | |   | (___) ||   \ | |   | |   | (___) || |      | |   | || (_____ 
 !   | |   |  ___  || (\ \) |   | |   |  ___  || |      | |   | |(_____  )
 !   | |   | (   ) || | \   |   | |   | (   ) || |      | |   | |      ) |
 !   | |   | )   ( || )  \  |   | |   | )   ( || (____/\| (___) |/\____) |
 !   )_(   |/     \||/    )_)   )_(   |/     \|(_______/(_______)\_______)
 !                                                                       
 !  Copyright W. Ryssens & M. Bender
 !
 !==============================================================================
 !
 ! Module containing the means to calculate (and print) the mean-field energy.
 ! Note that the actual coupling constants are contained in the constants.f90
 ! file. 
 !==============================================================================
 
 use compilation
 use geninfo
 use densities
 use parameterization
 use pairing

 implicit none
 
    !===========================================================================
    ! PARAMETERIZATION DEFINITION OPTIONS
    !===========================================================================
    !---------------------------------------------------------------------------
    ! Name of the parameterization
    character(len=20) :: name_param 
    ! Name of the functional file this code was compiled with
    character(len=20), parameter :: func_name = $FUNC_NAME

!    ! N3LO central
!    real(KIND=dp) :: t1n3= 2.3409
!    real(KIND=dp) :: t2n3=-2.31975
!    real(KIND=dp) :: x1n3=-0.344
!    real(KIND=dp) :: x2n3=-1.0 
!    !---------------------------------------------------------------------------
!    ! N2LO Tensor
!    ! Note that these are the constants from Michaels notes, that is to say 
!    ! 4 times as large as the ones in Danys/Lysandras notes
!    real(KIND=dp) :: ten2 =  40.0
!    real(KIND=dp) :: ton2 = -20.0  

    !---------------------------------------------------------------------------
    ! Definition of global contributions to the energy
    real(KIND=dp) :: Kinetic(2), Skyrme(2), TotalE, SpwfEnergy, Ehistory(5)
    real(KIND=dp) :: COMCorrection(2,2), CoulombDirect, CoulombExchange
    real(KIND=dp) :: PairingEnergy(2), PairDenEnergy(2)
    !===========================================================================
    ! NUMERICAL OPTIONS
    !===========================================================================
    !---------------------------------------------------------------------------
    ! Small non-zero value that can be used in a .func file to safeguard against
    ! division by zero. 
    real(KIND=dp) :: eps =1d-20
    !---------------------------------------------------------------------------
    ! Factor in the preconditioning of the F_I_I potential
    real(KIND=dp) :: preconfactor = 1.0_dp
    !---------------------------------------------------------------------------
    ! Type of preconditioning to apply
    integer       :: potentialpreconditioning = 1
    !===========================================================================
    ! AUTOMATICALLY GENERATED DECLARATIONS
    !===========================================================================
    !---------------------------------------------------------------------------
    ! Declaration of
    ! a) Coupling constants
    ! b) Terms in the energy
    ! c) Fields
    ! d) Previous_values of the fields
    ! All automatically generated by Hephaestos
    !---------------------------------------------------------------------------
$DECLARATION
    !---------------------------------------------------------------------------
      
contains

 subroutine readfunctional()
    !---------------------------------------------------------------------------
    ! Initializes the functional
    ! a) read the details of the parameterization from file
    ! b) calculate the coupling constants
    !---------------------------------------------------------------------------
    
    namelist /func/ name_param
    
    read(unit=*, nml=func) 
   
    name_param = to_upper(name_param)
    
    call readparameterization(name_param, func_name)
    call calcedfcoefs()

    !---------------------------------------------------------------------------
    ! Put the pairing routines pointers to the action of Delta
    delta_action_BCS => delta_action
    delta_action_HFB => delta_action
    
 end subroutine readfunctional
 
 subroutine calcedfcoefs()
     !--------------------------------------------------------------------------
     ! Calculate the coupling constants from the expressions passed into 
     ! Hephaestos.
     !
     !--------------------------------------------------------------------------
$CALCCOEF
    
    nucleonmass = 0.5*(nucleonmass(1) + nucleonmass(2))
 
 end subroutine calcedfcoefs
 
 subroutine printfunctional
    !---------------------------------------------------------------------------
    ! Print all information on the functional.
    !---------------------------------------------------------------------------
    call printparameterization(name_param, func_name)
    call printedfcoefs
    
 end subroutine printfunctional
 
 subroutine printedfcoefs
    !---------------------------------------------------------------------------
    ! Print the values of the EFD coefs used.
    !---------------------------------------------------------------------------
    1 format (' - - - - - - - - - - -')
    2 format (5x, 58('_'))
    3 format (' Skyrme coupling constants ')
    4 format (38x, 'Isospin representation')
    5 format (36x, '  C_0            C_1    ')
    6 format (38x, 'BFH representation ')
    7 format (36x, '  C_0            C_q    ')
    
    print 1
    print 3
    print 2
    print 4
    print 5
    print 2
    ! This part is automatically generated by Hephaestos.
$PRINTCOEF_ISO
    print 2
    print 6
    print 7
$PRINTCOEF_PN
    print 2
 end subroutine printedfcoefs

 subroutine PrintEnergy()
    !---------------------------------------------------------------------------
    ! Print all of the information on the energy.
    !---------------------------------------------------------------------------
    use Coulombmod
    
    1 format (80('-'))
    5 format (30x, '       neutron        proton         total')
    6 format (15x, ' Kinetic Energy:', 3f15.6)
   61 format (15x, '     COM 1-body:', 3f15.6)
   62 format (15x, '     COM 2-body:', 3f15.6)
    7 format (15x, ' Coulomb Direct:', 3f15.6)
   71 format (15x, '   Dir. (point):', 3f15.6)
    8 format (15x, '       Exchange:', 3f15.6)
   81 format (15x, '   Exc. (point):', 3f15.6)  
    9 format (15x, 'Pairing (delta):', 3f15.6)
   91 format (15x, 'Pairing (densi):', 3f15.6)
   99 format (15x, '   Total energy:', 30x, f15.6)
  100 format (15x, '     from spwfs:', 30x, f15.6)

    real(KIND=dp) :: temp

    call printSkyrme

    print 1
    print 5
    print 6, Kinetic, sum(Kinetic)
    print 61, COMcorrection(1,:), sum(COMcorrection(1,:))
	  if(any(COMcorrection(2,:).ne.0)) then
		 print 62, COMcorrection(2,:), sum(COMcorrection(2,:))
	  endif
    print *
    print 7, 0.0, CoulombDirect, CoulombDirect
    if(protonsize.ne.0 .and. (.not. protonsize_selfconsistent)) then
      temp = CoulombEnergy_Direct(D_I_I(:,2))
      print 71, 0.0, temp, temp
    endif
    print 8, 0.0, CoulombExchange, CoulombExchange
    if(protonsize.ne.0 .and. (.not. protonsize_selfconsistent)) then
      temp = CoulombEnergy_Exchange(D_I_I(:,2))
      print 71, 0.0, temp, temp
    endif
    print *
    print 9 , PairingEnergy, sum(PairingEnergy)
    print 91, PairDenEnergy, sum(PairDenEnergy)
    print 1
    print  99, TotalE
    print 100, spwfenergy
    print 1
 end subroutine PrintEnergy
 
 subroutine CalcEnergy
    !---------------------------------------------------------------------------
    ! Calculate all of the relevant energies.
    !---------------------------------------------------------------------------
    
    use Coulombmod

    integer :: i
    
    ! Kinetic energy
    Kinetic = CompKinetic()
    ! COM correction
    call CompCOMCorrection()
    ! Skyrme functional
    call compSkyrme()

    ! Pairing energy: can be used to check the validity of the calculation. 
    ! It is summed by integrating Delta instead of the pairing densities. 
    PairingEnergy = CalcPairingEnergy()


    if(protonsize_selfconsistent .or. protonsize.eq.0.0) then
      ! Direct contribution of the Coulomb potential
      CoulombDirect   = CoulombEnergy_Direct(D_I_I(:,2))
      ! Exchange contribution
      CoulombExchange = CoulombEnergy_Exchange(D_I_I(:,2)) 
    else
      ! Direct contribution of the Coulomb potential
      CoulombDirect   = CoulombEnergy_Direct(ChargeDensity)
      ! Exchange contribution
      CoulombExchange = CoulombEnergy_Exchange(ChargeDensity) 
    endif

    ! Saving history
    do i=4,1,-1
        Ehistory(i+1) = Ehistory(i)
    enddo
    Ehistory(1) = TotalE    

    ! Total energy
    TotalE = sum(Skyrme + Kinetic) + sum(COMCorrection)
    TotalE = TotalE + CoulombDirect + CoulombExchange

    ! Total energy from single-particle energies
    SpwfEnergy = calcspwfenergy()

 end subroutine CalcEnergy
 
 subroutine CompSkyrme()
    !---------------------------------------------------------------------------
    ! Calculate the Skyrme part to the functional.
    !---------------------------------------------------------------------------
    real(KIND=dp) :: Edensity(mv,3)
    integer       :: m
    
$CALCULATION
    
    Skyrme = &
$TOTAL

    PairDenEnergy = &
$TOTALPAIR

 end subroutine CompSkyrme
 
 subroutine PrintSkyrme()
    !---------------------------------------------------------------------------
    ! Print all contributions to the Skyrme energy, automatically generated by
    ! Hephaestos. 
    !---------------------------------------------------------------------------
    
    1 format (80('-'))
    2 format (' Skyrme Energy ')
    3 format (35x, 'Isoscalar      Isovector   |   Total')
    4 format (17x, 'Total Skyrme:', 3f15.6)
    
    print 1
    print 2
    print 3
    print 1
    
$PRINT

    print 1
    print 4, Skyrme, sum(Skyrme)
    print 1
 end subroutine PrintSkyrme

 function CompKinetic() result(kinetic)
    !---------------------------------------------------------------------------
    ! This subroutine computes the total kinetic energy,
    ! according to the following formula:
    !    E_k = -\hbar/2m \int d^3x \sum_{k} v_{k} \Psi_k^* \Delta \Psi_k
    !---------------------------------------------------------------------------
    ! Note that the 1-body c.o.m. correction is not taken into account here!
    !---------------------------------------------------------------------------
    use Constants

    integer          :: wave, it,k,i
    real(KIND=dp)    :: Inproduct
    real(KIND=dp)    :: Kinetic(2)
    
    ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ! Correctly set the pointers to the spwfs
    ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    select case(PairingType)
    case(0,1)
      ! HF or BCS Calculation
      DenPsi   => HFPsi    ; DenDPsi   => HFDPsi 
      DenddPsi => HFddPsi  ; DendddPsi => HFdddpsi
    case(2)
      ! HFB calculation
      DenPsi    => CanPsi   ; DenDPsi   => CanDPsi 
      DenddPsi  => CanddPsi ; DendddPsi => Candddpsi
    end select

    ! Kinetic Energy
    Kinetic = 0.0_dp
    do wave=1,nwt
        ! Isospin is neutron in the first half of blocks, proton in the rest
        it = 2
        if(wave.le.sum(HFBlocks(1:Blocks/2))) it = 1

        Inproduct = 0.0_dp
        do k=1,4          
                do i=1,mv
                       Inproduct = Inproduct + DenPsi(i,k,wave) *  & 
                       &  ( DenddPsi(i,1,k,wave) + &
                       &    DenddPsi(i,4,k,wave) + &
                       &    DenddPsi(i,6,k,wave))
                enddo
        enddo
        Kinetic(it)= Kinetic(it) + rho_can(wave)*Inproduct
    enddo
    Kinetic=-Kinetic * hbm * dv
    return
  end function CompKinetic
  
  subroutine CompCOMCorrection()
    !---------------------------------------------------------------------------
    ! M. Bender et al., Eur. Phys. J. A 7, 467-478 (2000)
    !
    ! For EV8-like symmetries, we have
    !
    !
    ! E_ph = + sum_km v^2_k v^2_m [ Re{nabla_x},k,m . Re{nabla_x},k,m          
    !                              +Im{nabla_y},k,m . Im{nabla_y},k,m     
    !                              +Re{nabla_z},k,m . Re{nabla_z},k,m ]   
    !
    !
    ! E_pp = -2 sum_k,m>0 v_k u_k v_m u_m {-Re(nabla_x)k,m . Re(nabla_x)-k,-m   
    !                                      +Im(nabla_y)k,m . Im(nabla_y)-k,-m   
    !                                      +Re(nabla_z)k,m . Re(nabla_z)-k,-m } 
    !
    !
    !
    ! Note: this routine will need quite some work to be generalized to 
    !       different symmetry combinations. 
    !---------------------------------------------------------------------------
    integer       :: it, i,j
    real(KIND=dp) :: NablaMElements(3,2,nwt,nwt),temp(3,2), fac
    
    COMCorrection = 0.0_dp
    if(COM1Body .gt. 0) then
      !Deduce 1-body COM correction from the Kinetic Energy
      COMCorrection(1,:) = - Kinetic(:) * nucleonmass/ &
      &                 (neutrons * nucleonmass(1) + protons * nucleonmass(2))
    endif
    
    if(COM2body .eq. 1) then
      ! Calculate 2-body COMcorrection
      NablaMElements = compNablaMelements()
      
      COMCorrection(2,:) = 0.0
      ! We sum carelessly over all single-particle wavefunctions, since the
      ! ones forbidden by symmetry are calculated as zero in the Spwfstorage
      ! module.

      !-------------------------------------------------------------------------
      ! particle-hole, and particle-particle part.
      ! We abuse the current symmetries here
      !-------------------------------------------------------------------------
      temp = 0
      do i=1,nwt
        it = 1
        if(i.gt.nwn) it = 2
        do j=1,nwt  
        
            fac = rho_can(i)*rho_can(j) + kappa_can(i)*kappa_can(j)
                    
            temp(1,it) = temp(1,it) + fac*NablaMElements(1,1,i,j)**2
            temp(2,it) = temp(2,it) + fac*NablaMElements(2,2,i,j)**2
            temp(3,it) = temp(3,it) + fac*NablaMElements(3,1,i,j)**2
        enddo
      enddo	
      !  Factor 0.5 = 0.25 * 2
      ! 0.25 since rho_can is double what it should be
      ! 2    since we are only summing over half of the states
      do it=1,2
			  COMCorrection(2,it) = 0.5*sum(temp(:,it))
      enddo
      ! Some constants
      COMCorrection(2,:) = COMCorrection(2,:) * hbm * nucleonmass/             & 
      &                 (neutrons * nucleonmass(1) + protons * nucleonmass(2))
     endif      

  end subroutine CompCOMCorrection

  subroutine calcFields()
    !---------------------------------------------------------------------------
    ! Calculate all of the Skyrme potentials.
    !- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ! Includes preconditioning of F_I_I at the moment only.
    !---------------------------------------------------------------------------
    use Coulombmod , only : SolveCoulomb, CoulombPotential, Exchangepotential
    use moments
    
    integer :: it,i,j,k
    real(KIND=dp), allocatable :: update(:,:)

$CALCFIELDS

    !---------------------------------------------------------------------------
    ! Solve for the Coulomb Potential
    call SolveCoulomb(D_I_I(:,2))
    
    !---------------------------------------------------------------------------
    ! Add the Coulomb contribution to the field corresponding to rho.
    do k=1,nz
      do j=1,ny
        do i=1,nx
          ! Direct contribution
          ! The index juggling is ugly, but necessary. The Coulomb potential
          ! is defined on a slightly larger box using boundary conditions.
          ! A simple abstract statement might mess this up.
          F_I_I(i+(j-1)*nx+(k-1)*ny*nx,2) =                                &
          &       F_I_I(i+(j-1)*nx+(k-1)*ny*nx,2) + CoulombPotential(i,j,k)
        enddo
      enddo
    enddo
    ! Exchange contribution
    F_I_I(1:mv,2) = F_I_I(1:mv,2) + ExchangePotential(1:mv)
    
    !---------------------------------------------------------------------------
    ! Add the contribution from the constraints on the electric multipole 
    ! moments. 
    F_I_I =  F_I_I + Constraint_I_I
    !---------------------------------------------------------------------------
    ! Precondition the field corresponding to rho, F_I_I.
    if(.not.all(F_I_I_hist.eq.0.0_dp) .and. potentialpreconditioning.eq.1) then
      if(.not.allocated(update)) allocate(update(nx*ny*nz,2))
    
      update=  F_I_I - F_I_I_hist
      update=  PreconditionPotential(update,-preconfactor,1.0_dp,+1,+1,+1)
      F_I_I =  F_I_I_hist + update
    endif
 
  end subroutine calcFields 
  
  function sphamil(psi, dpsi, ddpsi, dddpsi, sx,sy,sz,iso, onthefly) &
                                                                  & result(hpsi)
    !---------------------------------------------------------------------------
    ! Apply the action of the single-particle hamiltonian to the 
    ! single-particle wave-functions.
    !---------------------------------------------------------------------------
    
    use derivatives
    
    ! Logical indicating if the derivatives need to be calculated before
    ! applying h.
    ! If false, the derivatives are passed in. If True, the derivatives are not
    ! passed in and need to be calculated.
    logical, intent(in)       :: onthefly 
    
    real(KIND=dp), intent(in)    :: psi(mv,4)  
    real(KIND=dp), intent(inout) :: dpsi(mv,3,4),ddpsi(mv,6,4), dddpsi(mv,10,4)
    integer, intent(in)       :: sx(4),sy(4),sz(4),   iso
    real(KIND=dp)             :: hpsi(mv,4)
    real(KIND=dp)             :: temp(mv,4)
    real(KIND=dp)             ::   dtemp(mv,3,4)
    real(KIND=dp)             ::  ddtemp(mv,3,3,4)
    real(KIND=dp)             :: dddtemp(mv,3,3,3,4)
    real(KIND=dp)             :: laptemp(mv,4)
    
    real(KIND=dp)             :: ReducedMass
    
    integer :: it, i,k
    
    !---------------------------------------------------------------------------
    ! Determine the isospin index
    it = (iso + 3)/2
    !---------------------------------------------------------------------------
    ! Reduced mass in case of self-consistent 1-body COM correction
    if(COM1body .eq. 2) then
        Reducedmass = (1.0_dp-nucleonmass(it)/                                 &
        &                      (neutrons*nucleonmass(1)+protons*nucleonmass(2)))
    else
        Reducedmass = 1.0_dp
    endif
    
    if(OnTheFly) then
      ! Calculate the derivatives
      do k=1,4
!-------------------------------------------------------------------------------
$N2        call Derive_tot(psi(:,k),sx(k),sy(k),sz(k),dpsi(:,:,k),ddpsi(:,:,k))
$N3        call Derive_tot(psi(:,k),sx(k),sy(k),sz(k),dpsi(:,:,k),ddpsi(:,:,k),&
$N3        &                                     dddpsi(:,:,k))
!-------------------------------------------------------------------------------
        enddo
    endif
    !---------------------------------------------------------------------------
    ! Action of the kinetic energy
    do k=1,4
        do i=1,mv
            hpsi(i,k) = - hbm(it)* reducedmass *       (ddpsi(i,1,k) &
            &                                         + ddpsi(i,4,k) &
            &                                         + ddpsi(i,6,k)) 
        enddo
    enddo
    !---------------------------------------------------------------------------
    ! Action of the Skyrme fields
    !
    ! Note that 
    ! a) Coulomb is included in the F_I_I field
    ! b) Every density contains the contributions from constraints on that 
    !    density. 
    ! c) The kinetic energy is NOT included in the F_N_N field, because 
    !    a constant is not in the Lagrange basis; so the current way of
    !    deriving stuff is not correct for a term of the form
    !          hbar^2_2m
    !---------------------------------------------------------------------------
$SKYRMEACTION
    
  end function sphamil
  
  function delta_action(psi, dpsi, ddpsi, dddpsi, sx,sy,sz,iso, onthefly)      &
  &                                                             result(deltapsi)
    !---------------------------------------------------------------------------
    ! Logical indicating if the derivatives need to be calculated before
    ! applying delta.
    ! If false, the derivatives are passed in. If True, the derivatives are not
    ! passed in and need to be calculated.
    logical, intent(in)       :: onthefly 
    
    real(KIND=dp), intent(in)    :: psi(mv,4)  
    real(KIND=dp), intent(inout) :: dpsi(mv,3,4),ddpsi(mv,6,4), dddpsi(mv,10,4)
    integer, intent(in)       :: sx(4),sy(4),sz(4),   iso
    real(KIND=dp)             :: deltapsi(mv,4)
    real(KIND=dp)             :: temp(mv,4)
    real(KIND=dp)             ::   dtemp(mv,3,4)
    real(KIND=dp)             ::  ddtemp(mv,3,3,4)
    real(KIND=dp)             :: dddtemp(mv,3,3,3,4)
    real(KIND=dp)             :: laptemp(mv,4)
    
    integer :: it, i,k
    
    !---------------------------------------------------------------------------
    ! Determine the isospin index
    it = (iso + 3)/2
    
    !---------------------------------------------------------------------------
    ! Zero the action of Delta. 
    ! This is the place to include Coulomb pairing etc...
    deltapsi = 0.0
   
$PAIRINGACTION
   
  end function delta_action
  
  function calcspwfenergy() result(spwfenergy)
    !---------------------------------------------------------------------------
    ! Calculates the total energy from the single-particle energies. 
    !
    !---------------------------------------------------------------------------
    
    use wavefunctions
    use moments
    
    integer       :: wave
    real(KIND=dp) :: spwfenergy, e_rear
    
    ! Start by summing the single-particle energies
    spwfenergy = 0 ; e_rear = 0
    do wave=1,nwt
        if(pairingtype.lt.2) then
          spwfenergy = spwfenergy + rho_can(wave) * spenergies(wave)
        else
          spwfenergy = spwfenergy + rho_can(wave) * canenergies(wave)
        endif
    enddo
    
    ! Calculation of rearrangement energy (without Coulomb Exchange)
$EREAR   

    ! Add the rearrangement energy 
    spwfenergy = spwfenergy - e_rear 
    
    ! Add everything and don't forget about Coulomb exchange
    spwfenergy = 0.5 * spwfenergy + 0.5 * sum(kinetic) + CoulombExchange/3.d0
    
    ! Always add the 1-body COMcorrection. In case it is used iteratively, it
    ! is double counted along with the kinetic energy!
    if(COM1body.gt.0) then
        SpwfEnergy = SpwfEnergy  + sum(COMCorrection(1,:))/2.0_dp
    endif

    if(COM2body.gt.0) then
        SpwfEnergy = SpwfEnergy  + sum(COMCorrection(2,:))  
    endif
    
    !Subtract contribution by constraints
    SpwfEnergy = SpwfEnergy - sum(Constraint_I_I * D_I_I)*dv/2.0_dp
    
    ! Add the pairing energy
    SpwfEnergy = SpwfEnergy + sum(PairingEnergy)
    
  end function calcspwfenergy
  
  subroutine output_Edensity(Edensity, N)
    !---------------------------------------------------------------------------
    ! Write the energydensity to a file with name N.
    !
    !
    !---------------------------------------------------------------------------
    character(len=*), intent(in)   :: N
    real(KIND=dp), intent(in), target ::  Edensity(nx*ny*nz,3)
    real(KIND=dp), pointer :: w(:,:,:,:)
    
    real(KIND=dp) :: r,x
    integer       :: i
    
    w(1:nx,1:ny,1:nz,1:3) => Edensity
    
    open(12, File=N)
    
    do i=1,nx
      x = dx/2 + (i-1)*dx
      r = sqrt(3*x**2)
      write(12, '(5f10.5)') r, w(i,i,i,1),  w(i,i,i,2),  w(i,i,i,3) 
    enddo
    close(12)
  end subroutine output_Edensity
end module functional
