module moments
!===============================================================================
!  #######   ##   #    # #####   ##   #      #    #  ####
!     #     #  #  ##   #   #    #  #  #      #    # #
!     #    #    # # #  #   #   #    # #      #    #  ####
!     #    ###### #  # #   #   ###### #      #    #      #
!     #    #    # #   ##   #   #    # #      #    # #    #
!     #    #    # #    #   #   #    # ######  ####   ####
!
!  Copyright W. Ryssens & M. Bender
!
!===============================================================================
! 
! Module treating the calculation of, printing of and constraints on the 
! multipole moments of the various mean-field densities. 
!
! Spherical harmonics are taken to be in the convention of Messiah.
! They are, in terms of spherical coordinates:
!
!        Y_{l}^{m} = (-1)^{m}[(2*l+1)/4\pi (l-m)!/(l+m)!]^{1/2}
!                 *    P^{m}_{l}(cos(\theta)) e^{i m \phi}
!
! where the P^{m}_{l} are the associated Legendre Polynomials and -l <= m <= l.
! These expression on the mesh are automatically generated by recursion formula.
!
! The code "talks" about the real and imaginary parts of these moments.
! The only values for m that appear in the code are positive.
!
!   Re Y_lm =  1/2 * (Y_l+m + Y_l-m)
!   Im Y_lm = -i/2 * (Y_l+m - Y_l-m)
!
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
! 
! The electric multipole moments are
!      \langle \hat{Q}^e_{lm} \rangle = \int d^3r rho(r) r^l Y_{lm} 
! The magnetic multipole moments are
!      \langle \hat{Q}^m_{lm} \rangle = Q^m_lm,spin + Q^m_lm,orbit 
!      Q^m_lm,spin                = 0.5*\int d^3r s_m(r) nabla_m(r^l Y_{lm}) 
!      Q^m_lm,orbit               =     \int d^3r (rxj)_m(r) nabla_m(r^l Y_{lm}) 
!
! Note that the magnetic moments are not calculated in this way by the code, 
! but rather by partial integration and using a vector identity for the orbit
! part.
!
! The magnetic multipole moments do not appear yet in this code, as they are
! time-odd.
!
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! The rms radius is treated on the same footing as the multipole moments here
! even though there is no spherical harmonic corresponding to it. It is put into
! the linked list for l=-1. 
!
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! For the electric multipole moments, practical quantities to investigate are
!
! Dimensionless deformation Betas
!  Beta_lm  = 4 * pi /( 3 * R_0**l * A) < Q^e_{lm} >
!           where R0 = 1.2A**(1/3)
!
! Total deformation
!  Q_l = \sqrt{ \Sum_{m = 0,..,l} f(m) [ < Re Q_{lm} >**2 + < Im Q_{lm}**2 > ]}
!         with f(m) = 2 if m \not = 0 and f(m) = 1 for m = 0.
!
! For more conversion formulae see:
!
!   W.Ryssens, V. Hellemans, M. Bender & P.-H. Heenen, CPC 187 (2015) 175-194
!   W.Ryssens, PhD Thesis (2016)
!
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
!
!  For constraints, two options exist for every moment independently
!  - Augmented Lagrangian with fixed intensity
!  - Constraints with projection on feasible set
!
!  This is encoded for every multipole moment separately 
!   (0) No constraint
!   (1) Augmented Lagrangian
!   (2) Projection on feasible set
!
!  For the moment only the total value of the electric multipole moments can be
!  constrained. 
!
!-------------------------------------------------------------------------------
!
! There is a redundancy in the choice of parameterization of the multipole 
! moments: it depends on the choices made for the Cartesian reference frame. 

! There are six possibilities, corresponding to the permutations of the 
! axes of the intrinsic frame. 
!
! (x,y,z), (x,z,y), (y,x,z), (y,z,x), (z,x,y), (z,y,x)
!
! which all correspond to different parameterizations of the spherical
! coordinates in terms of (x,y,z).
!
! The distinction is made by two parameters:
!     QuantisationAxis = X/Y/Z (1,2,3)
! which determines which of the Cartesian coordinates determines the 
! azimuthaml angle theta
!     x_i = r cos(theta).
! The second parameter
!     SecondaryAxis = 1/2
! simply determines the reference for the angle \phi. It determines the order of
! the two other (non-quantization) axes. 1 corresponds to lexographical order
! (x,y) while 2 corresponds to non-lexicographical order (y,x).
!
! The angle phi is determined by
!     \phi = atan2(x_2, x_1)
!
! Examples:
!    (QuantisationAxis, SecondaryAxis,Permutation)
!    (3,1, (x,y,z))
!    (3,2, (y,x,z))
!    (2,1, (x,z,y))
!    (2,2, (z,x,y))
!    (1,1, (y,z,x))
!    (1,2, (z,y,x))
!
! Note that changing from the ordinary (x,y,z) has profound consequences
! regarding which non-physical multipole moments. 
!-------------------------------------------------------------------------------
!===============================================================================
  use geninfo
  use sphericalharmonics

  implicit none
  
  !-----------------------------------------------------------------------------
  ! The technical feat of treating multipole moments on an equal footing for 
  ! any kind of (l,m) or nature of the multipole moment is accomplished by 
  ! using several linked lists of these moment type objects.
  !-----------------------------------------------------------------------------
  type Moment
      !-------------------------------------------------------------------------
      !Principal and magnetic quantum number of the multipole moment
      integer :: l,m
      !Looking at the real(.false.) or imaginary(.true.) part
      logical :: ImPart
      ! Nature of the multipole moment. 
      ! Accepted values:
      ! a) electric
      integer :: momtype
      !-------------------------------------------------------------------------
      !The SpherHarm variable contains the values of the associated Qlm.
      !-------------------------------------------------------------------------
      real(KIND=dp), allocatable  :: SpherHarm(:)
      !-------------------------------------------------------------------------
      ! Integer controlling the type of constraint on the multipole moment.
      ! 0 - unconstrained
      ! 1 - Augmented Lagrangian
      ! 2 - Projection on feasible set
      !-------------------------------------------------------------------------
      integer       :: ConstraintType
      !-------------------------------------------------------------------------
      ! Number of iterations to employ the constraint for. Useful for putting 
      ! temporary constraint in order to initialize a calculation.
      integer       :: Iteration=-1
      !-------------------------------------------------------------------------
      ! Calculated value of the moment with and without cutoff,
      ! for neutrons and protons.
      !-------------------------------------------------------------------------
      real(KIND=dp) :: Value(2)
      !-------------------------------------------------------------------------
      ! Value of the multipole at the previous iteration
      real(KIND=dp) :: history(2)
      !-------------------------------------------------------------------------
      ! Calculated value of the moment SQUARED.
      ! So < Q_{lm}^2 > and < Q_{lm}>^3
      !-------------------------------------------------------------------------
      real(KIND=dp) :: Squared(2)
      !-------------------------------------------------------------------------
      ! Value of the constraint on the multipole moment.
      real(KIND=dp) :: Constraint
      !-------------------------------------------------------------------------
      ! Value of the current value of the Lagrange multiplier
      real(KIND=dp) :: multiplier
      !-------------------------------------------------------------------------
      ! Deviation of the constraint with respect to the asked for value.
      real(KIND=dp) :: deviation
      !-------------------------------------------------------------------------
      ! Intensity of the constraint
      real(KIND=dp) :: Intensity
      !-------------------------------------------------------------------------
      ! Pointers to the previous and next item in the linked list.
      !-------------------------------------------------------------------------
      type(Moment), pointer  :: Prev
      type(Moment), pointer  :: Next
      !-------------------------------------------------------------------------
      ! Deformation parameter Beta_lm associated with the moment.
      ! (neutrons,protons,total)
      !-------------------------------------------------------------------------
      real(KIND=dp) :: Beta(3)
      !-------------------------------------------------------------------------
      ! Logical: if True, use the Lagrange multiplier as read from file.
      logical :: multfromfile = .false.
      logical :: continue     = .false.
      !-------------------------------------------------------------------------
      ! Procedure pointer to the routine used to calculate the moment.
      procedure(Calculate_electric),   pointer, nopass :: Calculate
      !-------------------------------------------------------------------------
      ! Procedure pointer to the routine used to print output of the moment.
      procedure(PrintMoment_electric), pointer, nopass :: PrintMoment
      !-------------------------------------------------------------------------
  end type Moment

  !-----------------------------------------------------------------------------
  !Maximum degree of the multipole components that are considered. Default = 10
  integer      :: MaxMoment=10, maxmoment_J0=2
  !-----------------------------------------------------------------------------
  ! Starting point for the linked list of moments.
  !-----------------------------------------------------------------------------
  type(Moment),save, pointer :: Root         ! Electric multipole moments
  !-----------------------------------------------------------------------------
  ! CutoffType
  ! 0 : Density-dependent cutoff
  ! 1 : Spherical cut-off
  !-----------------------------------------------------------------------------
  integer       :: CutoffType=0
  !-----------------------------------------------------------------------------
  !Parameters of the cutoff function.
  ! 1 + exp[(\DeltaR - radd)/acut]
  ! Default values are the ones from K. Rutz et al, Nucl. Phys. A590 (1995) 690
  !-----------------------------------------------------------------------------
  real(KIND=dp) :: radd = 4._dp,acut=0.4_dp
  !-----------------------------------------------------------------------------
  !Cutoff function
  ! For 1) Neutrons, 2) Protons
  real(KIND=dp), allocatable, target :: Cutoff(:,:)
  !-----------------------------------------------------------------------------
  ! Slowdown of the readjustment of the Lagrange multipliers
  !-----------------------------------------------------------------------------
  real(KIND=dp)  :: ReadjustSlowDown=0.1_dp
  !-----------------------------------------------------------------------------
  !Pointer to the cutoff procedure chosen.
  !-----------------------------------------------------------------------------
  abstract interface
        subroutine comp_cutoff()
        end Subroutine
  end interface
  procedure(comp_cutoff), pointer :: CompCutoff
  !-----------------------------------------------------------------------------
  ! Quadrupole moments in different representations, for printing purposes only.
  !
  ! Cartesian: QCartesian
  ! (Q,gamma): Q, G
  ! iq1, iq2 : iq1, iq2
  !-----------------------------------------------------------------------------
  real(kind=DP)   :: QCartesian(3,3,3), Q(3), G(3), iq1(3), iq2(3)
  !-----------------------------------------------------------------------------
  ! Quantisation axis of the moments.
  integer :: QuantisationAxis=3, SecondaryAxis=1
  !-----------------------------------------------------------------------------
  ! Contribution to the single-particle Hamiltonian by the constraints
  !  a) Electric multipole => Constraint_I_I => F_I_I
  !-----------------------------------------------------------------------------
  real(kind=dp), allocatable, target :: Constraint_I_I(:,:)
  !-----------------------------------------------------------------------------
  ! If true, the code takes ALL of the information on the constrained moments
  ! from the read-in wavefunction file.
  logical :: ContinueAll = .false.

contains
  
  subroutine IniMoments()
    !---------------------------------------------------------------------------
    ! This routine sets up all of the linked lists needed.
    ! 
    ! 1) The first moment ( l=0, m=0 ) is created. It is called 'Root'.
    !    
    ! 2) The values of all the desired spherical harmonics
    !    (l=0,..., MaxMoment, m=0,...,MaxMoment) are computed.
    !
    ! 3) The routine creates all the necessary moments using subroutine
    !    NewMoment and links them in the following order:
    !    (l,m, R/I): (0,0), (1,0), (1,1,R), (1,1,I), (2,0), (2,1,R), (2,1,I),...
    !    Moments that are automatically zero (by symmetry) are not created by
    !    NewMoment and are absent from the list.
    ! 
    ! 4) Tantalus here detects the nonphysical moments. Not yet applicable to 
    !    this version.
    !
    ! 5) After all this, a final addition to the linked list is made: the
    !    radius squared. (This can be used to calculate the rms radius
    !    obviously).
    !
    ! --------------------------------------------------------------------------
    integer :: l,m,ImPart,i,j,k
    ! Meshes containing the values of all associated Legendre Polynomials
    ! Some dimensions start at index 0, because l and m can both be 0
    real(KIND=dp),allocatable  :: SpherHarmMesh(:,:,:,:,:,:)
    type(Moment),pointer       :: NextMoment,Current
    
    real(KIND=dp), pointer     :: harm_3D(:,:,:)
    
    allocate(SpherHarmMesh(nx,ny,nz,0:MaxMoment,0:MaxMoment,2))
    
    !---------------------------------------------------------------------------
    ! Create the first Multipole moment: l=0, m=0
    nullify(Root) ;    allocate(Root)
    Root%l=0      ;    Root%m=0
    allocate(Root%SpherHarm(nx*ny*nz))
    
    !---------------------------------------------------------------------------
    !This is the l=0,m=0 spherical harmonic
    Root%SpherHarm=1.0_dp/sqrt(4.0_dp*pi) 
    Root%Impart=.false.
    Root%ConstraintType=0
    Root%Calculate   => Calculate_electric
    Root%PrintMoment => PrintMoment_electric
    nullify(Root%Prev) ;  nullify(Root%Next)
    
    !---------------------------------------------------------------------------
    ! Calculating all the spherical harmonics
    call GenSphericalHarmonics(maxmoment,nx,ny,nz,meshx,meshy,meshz,           & 
    &                          SpherHarmMesh,quantisationaxis,secondaryaxis)
    
    !---------------------------------------------------------------------------
    ! Starting the initialization
    nullify(Current)      ;  allocate(Current)     ; Current=>Root
    nullify(Current%Next) ;  nullify(Current%Prev) ; nullify(NextMoment)
    
    !---------------------------------------------------------------------------
    !Creating all the moments and assigning each moment the spherical harmonic
    ! a) The electric moments
    do l=1, MaxMoment
      do m=0,l
        do ImPart=0,1
          NextMoment => NewMoment_electric(l,m,ImPart)
          !Placing the moment in the list
          if(associated(NextMoment)) then
            harm_3D(1:nx,1:ny,1:nz) => NextMoment%SpherHarm(:)
            harm_3D=SpherHarmMesh(:,:,:,l,m,Impart+1)
            ! Putting the pointers in the correct direction
            NextMoment%Prev => Current
            Current%Next    => NextMoment
            Current         => NextMoment
            nullify(NextMoment)
          endif
        enddo
      enddo
    enddo
    !---------------------------------------------------------------------------
    !Appending the radius squared to the ordinary list
    NextMoment   => NewMoment_electric(-2,0,0)
    harm_3D(1:nx,1:ny,1:nz) => NextMoment%SpherHarm(:)
    NextMoment%Calculate    => Calculate_rms  

    do k=1,nz
      do j=1,ny
        do i=1,nx
          harm_3D(i,j,k) = meshx(i)**2 + meshy(j)**2 + meshz(k)**2
        enddo
      enddo
    enddo
    
    Current%Next    => NextMoment
    NextMoment%Prev => Current
    !---------------------------------------------------------------------------
    return
  end subroutine IniMoments

  function NewMoment_Electric(l,m,ImPart) result(newmoment)
    !---------------------------------------------------------------------------
    ! This subroutine creates a new electric multipole moment, provided the 
    !                                                         symmetries permit.
    !
    ! Will need some serious work and adaptation by Tantalus.
    !---------------------------------------------------------------------------
    type(Moment),pointer   :: NewMoment
    integer, intent(in)    :: l,m,ImPart

    nullify(NewMoment)

    !---------------------------------------------------------------------------
    ! Selection rules, independent of axis choices.
    if((mod(l,2).ne.0)) then
      ! The multipole moments of odd order are constrained by parity.
      return
    endif

    if((m.eq.0).and.(Impart.eq.1)) then
      !Do not create a new moment for an imaginary part of moments with m=0
      return
    endif
    !---------------------------------------------------------------------------
    ! Selection rules, dependent of axis choices.
    select case(QuantisationAxis)
    case(1)
        ! Conservation of y-timesimplex
        if((ImPart.eq.1.)) then
          return
        endif
        ! Conservations of signature
        if((mod(m,2).ne.0)) then
          return
        endif
    case(2)
        if((mod(l,2) .ne. 0) .and. (mod(m,2).eq.0)) then
         return
        endif
        if((mod(l,2) .eq. 0) .and. (mod(m,2).ne.0) ) then
          return
        endif

        if((Impart.eq.0) .and. (mod(m,2).ne.0)) then
          return
        endif
        if((Impart.eq.1) .and. (mod(m,2).eq.0)) then
          return
        endif
    case(3)
        if((ImPart.eq.1.)) then
          return
        endif
        if((mod(m,2).ne.0)) then
          return
        endif
    end select 
    !---------------------------------------------------------------------------
    allocate(NewMoment) ; NewMoment%l=l ; NewMoment%m=m

    nullify(NewMoment%Prev, NewMoment%Next) 
    allocate(NewMoment%SpherHarm(nx*ny*nz))

    if(ImPart.eq.1.) then
        NewMoment%ImPart=.true.
    else
        NewMoment%ImPart=.false.
    endif

    ! The parameters of the new multipole moment are set to zero by default.
    NewMoment%ConstraintType= 0
    NewMoment%Value         = 0.0_dp
    NewMoment%SpherHarm     = 0.0_dp
    NewMoment%Squared       = 0.0_dp

    nullify(NewMoment%Calculate)
    NewMoment%Calculate   => Calculate_electric
    NewMoment%PrintMoment => PrintMoment_electric

    return
  end function NewMoment_Electric

!===============================================================================
! Calculation routines
!
!===============================================================================
  subroutine CalculateMoments()
    !---------------------------------------------------------------------------
    ! Subroutine that
    !   1) Calculates the values of all multipole moments
    !   2) Calculate the quadrupole moments in different representations
    !---------------------------------------------------------------------------
    use Densities
    
    type(Moment), pointer :: Current

    nullify(Current)
    Current => Root
    !---------------------------------------------------------------------------
    !First, we need to calculate the cutoff function
    call CompCutoff
    !---------------------------------------------------------------------------
    ! Calculate the electric monopole
    call Current%Calculate(Current)
    !---------------------------------------------------------------------------
    ! Calculate the electric multipole moments
    do while(associated(Current%Next))
        Current => Current%Next
        call Current%Calculate(Current)
    enddo

    call CalcQuadrupoleAlt()

    return
  end subroutine CalculateMoments
  
  subroutine Calculate_electric(ToCalculate)
    !---------------------------------------------------------------------------
    ! This subroutine calculates the passed-in electric multipole moment.
    !---------------------------------------------------------------------------
    use Densities, only : D_I_I
  
    1 format ('Nan in Q_{ ,' i2, ' ', i2, '}')
    
    class(Moment),        intent(inout) :: ToCalculate
    integer                             :: it

    ! Save the history
    Tocalculate%history = tocalculate%value

    !Initialise
    ToCalculate%Value      = 0.0_dp
    ToCalculate%Squared    = 0.0_dp

    !---------------------------------------------------------------------------
    ! Calculate the new value for ordinary constraints
    do it=1,2
      ToCalculate%Value(it)    = ToCalculate%Value(it) + &
      &       sum(ToCalculate%SpherHarm*D_I_I(:,it))
      ToCalculate%Squared(it)    = ToCalculate%Squared(it)    + &
      &       sum(ToCalculate%SpherHarm**2*D_I_I(:,it))
    enddo
    ToCalculate%Value     =ToCalculate%Value*dv
    ToCalculate%Squared   =ToCalculate%Squared*dv
    
    ! Check for problems
    if(any(ToCalculate%Value.eq.ToCalculate%Value+1)) then
      print 1, ToCalculate%l, ToCalculate%m
      stop
    endif

    ! Set the deviation
    if(ToCalculate%ConstraintType.ne.0) then
      ToCalculate%deviation    =                                               &
      &                     abs(sum(ToCalculate%Value) - ToCalculate%constraint)
    endif
    call CalcBeta(ToCalculate)

    return
  end subroutine Calculate_electric

  subroutine Calculate_rms(ToCalculate)
    !---------------------------------------------------------------------------
    ! Subroutine to calculate the rms radii of both nucleon species.
    ! This proceeds in the same way as the Calculate_electric, but is different
    ! since it possibly needs to include the folding for the finite size of the
    ! proton. 
    !---------------------------------------------------------------------------
    use densities, only : chargedensity, D_I_I

    class(Moment),        intent(inout) :: ToCalculate

    ! Save the history
    Tocalculate%history = tocalculate%value

    !Initialise
    ToCalculate%Value      = 0.0_dp
    ToCalculate%Squared    = 0.0_dp

    ! Neutron rms radius
    ToCalculate%Value(1)    = sum(ToCalculate%SpherHarm*D_I_I(:,1))
    ToCalculate%Squared(1)  = sum(ToCalculate%SpherHarm**2*D_I_I(:,1))

    ! The charge density in the Coulomb module includes the folding when it is 
    ! included in the functional.
    ToCalculate%Value(2)    =  &
    &                sum(ToCalculate%SpherHarm*   chargedensity(1:nx*ny*nz,1,1))
    ToCalculate%Squared(2)  =  &
    &                sum(ToCalculate%SpherHarm**2*chargedensity(1:nx*ny*nz,1,1))

    !  Volume elements
    ToCalculate%Value     = ToCalculate%Value   * dv
    ToCalculate%Squared   = ToCalculate%Squared * dv
    
    ! Set the deviation
    if(ToCalculate%ConstraintType.ne.0) then
      ToCalculate%deviation    =                                               &
      &                     abs(sum(ToCalculate%Value) - ToCalculate%constraint)
    endif
    call CalcBeta(ToCalculate)

  end subroutine Calculate_rms
  
  subroutine CalcBeta(Mom)
  !-----------------------------------------------------------------------------
  ! Function that calculates the beta_lm deformation parameters associated with
  ! an (electric) multipole moment Q_lm.
  !-----------------------------------------------------------------------------
    type(Moment), intent(inout) :: Mom
    real(KIND=dp)               :: R, factor

    R = 1.2_dp  * (neutrons + protons)**(1.0_dp/3.0_dp)
    factor = 4.0_dp * pi /(3.0_dp * (neutrons+ protons) * R**(Mom%l))

    Mom%Beta(1:2) = factor*Mom%Value
    Mom%Beta(3)   = factor*sum(Mom%Value)
  end subroutine CalcBeta
  
  subroutine CalcQuadrupoleAlt()
    !---------------------------------------------------------------------------
    ! Calculates the Quadrupole moments in their various representations.
    ! See the formulas in 
    !
    !   W. Ryssens, Symmetry breaking in nuclear mean-field models, 
    !     PhD Thesis, ULB (2016)
    !---------------------------------------------------------------------------
    ! The off-diagonal components of the quadrupole tensor are kept, but not
    ! used at the moment....
    !---------------------------------------------------------------------------
    type(Moment),pointer :: Q20, RQ22 , IQ22, RQ21, IQ21
    integer              :: i

    ! Finding the moments. Note that moments that are not allowed will not be
    ! found and the pointers will be null.
    Q20 =>FindMoment(2,0,.false.     )
    RQ21=>FindMoment(2,1,.false., Q20)
    IQ21=>FindMoment(2,1,.true. , Q20)
    RQ22=>FindMoment(2,2,.false., Q20)
    IQ22=>FindMoment(2,2,.true. , Q20)

    QCartesian = 0.0_dp

    !Cartesian Moments
    do i=1,2
      ! a) Diagonal elements
      QCartesian(1,1,i) = - (sqrt(5.0_dp/( 4.0_dp * pi)))**(-1)  * &
      &         ( Q20%Value(i) - sqrt(6.0_dp) * RQ22%Value(i) )
      QCartesian(2,2,i) = - (sqrt(5.0_dp/( 4.0_dp * pi)))**(-1)  * &
      &         ( Q20%Value(i) + sqrt(6.0_dp) * RQ22%Value(i) )
      QCartesian(3,3,i) =   (sqrt(5.0_dp/(16.0_dp * pi)))**(-1)  * &
      &           Q20%Value(i)

      ! b) Off-diagonal elements
      if(associated(RQ21)) then
        ! RQ21 = sqrt(15/(pi 4)) zx
        QCartesian(1,3,i) = RQ21%Value(i) * sqrt(4.0_dp * pi/ (15.0_dp))
        QCartesian(3,1,i) = QCartesian(1,3,i)
      endif
      if(associated(IQ21)) then
        !IQ21 = sqrt(15/(4 pi)) yz
        QCartesian(2,3,i) = IQ21%Value(i) * sqrt(4.0_dp * pi/ (15.0_dp))
        QCartesian(3,2,i) = QCartesian(2,3,i)
      endif
      if(associated(IQ22)) then
        !IQ22 = sqrt(15/(4*pi)) xy
        QCartesian(1,2,i) = IQ22%Value(i) * sqrt(4.0_dp * pi/ (15.0_dp))
        QCartesian(2,1,i) = QCartesian(1,2,i)
      endif
    enddo

    !Total moments
    QCartesian(:,:,3)=sum(QCartesian(:,:,1:2),3)

    !---------------------------------------------------------------------------
    ! Q & Gamma representation
    do i=1,3
      Q(i) = sqrt(2.0_dp/3.0_dp *                                              &
      &   ( QCartesian(1,1,i)**2 + QCartesian(2,2,i)**2 + QCartesian(3,3,i)**2))
      if(abs(QCartesian(3,3,i)).gt.1d-08 ) then
        G(i) = atan2((QCartesian(1,1,i) - QCartesian(2,2,i)),                  &
        &                                     (sqrt(3.0_dp)* QCartesian(3,3,i)))
      else
        G(i) = 0.0_dp
      endif
    enddo
    ! iq1 & iq2
    do i=1,3
      iq1(i) = Q(i) * cos(G(i)) - 1/sqrt(3.0_dp) * Q(i) * sin(G(i))
      iq2(i) = 2/sqrt(3.0_dp)*Q(i)*sin(G(i))
    enddo
  end subroutine CalcQuadrupoleAlt
  
  pure function LegacyQuad (iq1,iq2) result(Constraints)
    !---------------------------------------------------------------------------
    ! Function that converts the legacy iq1, iq2 input from EV8 to new style
    ! input on Q20 & Q22.
    ! See conversion coefficients in W.Ryssens et al., CPC (to be published)
    !---------------------------------------------------------------------------
    real(KIND=dp), intent(in) :: iq1,iq2
    real(KIND=dp)             :: Constraints(2)
    real(KIND=dp)             :: Q20, Q22
    Constraints=0.0_dp

    ! Q20 = 1/2 *sqrt(5/(16*pi))* ( 2 * q1 + q2)
    Q20 = 0.5_dp *sqrt(5.0_dp/(16.0_dp * pi)) * ( 2 * iq1 + iq2 )

    ! Q22 = 3/2*q2 * sqrt(5/(4*pi)) * 1/(2 * sqrt(6))
    Q22 = 1.5_dp * iq2 * sqrt(5.0_dp/(4.0_dp * pi)) /(2 * sqrt(6.0_dp))

    Constraints(1) = Q20
    Constraints(2) = Q22

  end function LegacyQuad
  
!===============================================================================
! Treatment of constraints, readjustment and contribution to sphamil. 
!===============================================================================
  
  subroutine Sphamilcontribution()
    !---------------------------------------------------------------------------
    ! This function calculates the energy contribution associated with the
    ! constraints on the multipole moments.
    !
    ! For ordinary multipole constraints
    !  h => h - \lambda * O 
    ! where lambda is the current multiplier
    !---------------------------------------------------------------------------
    integer               :: it
    type(Moment), pointer :: Current

    Current => Root
    
    Constraint_I_I = 0.0_dp
    do while(associated(Current%Next))
      Current => Current%Next

      ! Go to the next moment if this moment is not constrained
      if(Current%constrainttype.eq.0) cycle
     
      do it=1,2
        Constraint_I_I(:,it) = Constraint_I_I(:,it)                            &
        &                  - Current%Multiplier * Current%SpherHarm*Cutoff(:,it)
      enddo
    enddo
    nullify(Current)
    
  end subroutine SpHamilcontribution
  
  subroutine ReadjustAllMoments(ctype)
    !---------------------------------------------------------------------------
    ! Readjust all the multipole constraints of type ctype
    !---------------------------------------------------------------------------
    
    type(Moment), pointer :: Current
    integer, intent(in)   :: ctype

    nullify(Current)
    Current => Root

    do while(associated(Current%Next))
        Current => Current%Next
        if(Current%constrainttype .eq. ctype)  call Readjust(Current)
    enddo
    nullify(Current)
    
  end subroutine ReadjustAllMoments
  
  subroutine Readjust(ToReadjust)
    !---------------------------------------------------------------------------
    ! Subroutine that readjusts the constraint of a certain multipole moment.
    !---------------------------------------------------------------------------
    type(Moment), pointer    :: ToReadjust
    real(KIND=dp) :: slow

   11 format ( '------------------------------------')
   12 format ( ' Constraint on Q_{ ', 2i2, ' has no ')
   13 format ( ' intensity parameter.')
   14 format ( ' Estimated ', 1es12.5)
   
    if(ToReadjust%ConstraintType.eq.0) then
      print *, 'Moment is not constrained, but still gets readjusted!'
      stop
    endif

    ! Augmented Lagrangian readjustment
    if(ToReadjust%Intensity .eq. 0.0) then
          ! Find suitable intensity, if none was found before
          ToReadjust%Intensity = 1/sum(ToReadjust%Squared)
          print 11
          print 12, ToReadjust%l,ToReadjust%m
          print 13
          print 14, ToReadjust%Intensity
          print 11
    endif
    
    slow = ReadjustSlowdown
    if(Toreadjust%constrainttype.eq.2) slow = 1.0

    ! Set the new multiplier        
    ToReadjust%Multiplier =  ToReadjust%Multiplier +   slow *                  &
    &     ToReadjust%Intensity*(ToReadjust%Constraint - sum(ToReadjust%Value))

    return
  end subroutine Readjust

!===============================================================================
! In/output
!===============================================================================

  subroutine ReadMomentData(file_number)
    !---------------------------------------------------------------------------
    ! A subroutine that governs the input of this module.
    !---------------------------------------------------------------------------

    integer(dp), intent(in), optional   :: file_number   
  
    integer             :: iostat, iteration
    integer             :: l,m, ConstraintType
    real(KIND=dp)       :: Constraint, iq1=-1000000, iq2=-1000000, Intensity
    logical             :: MoreConstraints=.false., Impart, MultfromFile
    logical             :: continue
    type(Moment),pointer:: Current
    real(KIND=dp), allocatable:: LegacyCon(:)

    NameList /MomentParam/                                                     &
    &           QuantisationAxis, SecondaryAxis, MaxMoment, &  ! General options
    &           radd, acut, cutofftype,                     &   ! Cutoff options
    &           ContinueAll,                                &
    &           MoreConstraints            ! Signal that constraints will follow
      
    NameList /MomentConstraint/                                                &
    &          l,m, Impart,                    & ! Defining the multipole moment 
    &          Constraint,Intensity, ConstraintType, & ! Defining the constraint 
    &          iq1, iq2, Iteration, multfromfile, continue,                    &
    &          MoreConstraints        ! Signal that more constraints will follow

    nullify(Current)

    iostat = 0 ;  l = 1

    !Reading the parameters
    if(present(file_number)) then
      read(unit=file_number,NML=MomentParam )
    else
      read(unit=*,NML=MomentParam )
    endif

    if(QuantisationAxis.le.0 .or. QuantisationAxis .gt. 3) then
        print *, 'Illegal value of quantisation axis!'
        stop
    endif

    if(SecondaryAxis .le. 0 .or. SecondaryAxis .gt. 2) then
      print *, 'Illegal value of secondary axis!'
      stop
    endif

    !Initialising the Linked List
    call IniMoments()

    allocate(Constraint_I_I(nx*ny*nz,2))
    Constraint_I_I = 0.0_dp

    !Choosing cutoff
    nullify(CompCutoff)
    select case (CutoffType)
      case(0)
        !Rutz-Type cutoff
        CompCutoff => RutzCutoff
      case(1)
        !Spherical cutoff
        CompCutoff => StandardCutoff
      case default
        print *, 'Invalid choice of cutofftype. It can either be 0 or 1.'
        stop
    end select

!    !Constraining the non-physical degrees of freedom, if present
!    call ConstrainNonPhysicalMoments()

    ! Do-loop exits when MoreConstraints indicated no more constraints will
    ! follow.
    do while(MoreConstraints)
        !-----------------------------------------------------------------------
        !Initialisation
        l=0; m=0; Impart=.false.  ; Intensity      = 0.0_dp
        Constraint=0.0_dp         ; MoreConstraints=.false.   
        ConstraintType=2          ; MultfromFile   =.false. ; continue = .false.
        iq1=-1000000_dp           ; iq2=-1000000_dp ; iteration = -1 

        if(present(file_number)) then
          read(unit=file_number, NML=MomentConstraint, IOSTAT=iostat)
        else
          read(unit=*, NML=MomentConstraint, IOSTAT=iostat)
        endif

        if(iostat .ne. 0) then
          print *, "Input error for moment constraints." 
          stop
        endif
        !-----------------------------------------------------------------------
        !Finding the Correct Moment to constrain
        Current => FindMoment(l,m,Impart)

        if(.not.associated(Current)) then
          print *, "MOCCa can't find this moment!", 'l= ', l, ' m= ', m
          stop
        endif
  
        !-----------------------------------------------------------------------
        if((iq1.ne.-1000000_dp) .or. (iq2.ne.-1000000_dp)) then                
          if((l.ne.2) .or. (m.ne.2 .and. m .ne. 0)) then
            !Only allow iq1 & iq2 for Q20 and Q22
            print *, 'You specified legacy iq1,iq2 input for multipoles that ' &
            &        ,'are not Q20 or Q22.'
            stop
          else
            !Converting input
            allocate(LegacyCon(2))
            LegacyCon = LegacyQuad(iq1,iq2)
          endif
        endif
        !-----------------------------------------------------------------------
        !Setting the parameters of the moment
        Current%ConstraintType = ConstraintType
        Current%iteration      = iteration
        Current%Intensity = Intensity
        !Reading the values for the constraints
        if(ConstraintType.ne.0) then
              !-----------------------------------------------------------------
              ! Deal with legacy input
              if( allocated(LegacyCon)                                       &
              &  .and. l.eq. 2 .and. m.eq.2 .and. .not. Impart) then
                 ! Constraint on Q22 as dictated by iq1/iq2
                 Current%Constraint    = LegacyCon(2)
              elseif(allocated(LegacyCon)                                    &
              &  .and. l.eq. 2 .and. m.eq.0 .and. .not. Impart) then
                ! Constraint on Q20 as dictated by iq1/iq2
                Current%Constraint     = LegacyCon(1)
              else
                if(Current%l .eq. -2) then
                  print *, 'RMS radius constraint is not implemented'
                  stop
                elseif(Current%l .eq. 0) then
                  print *, 'You cannot constrain the number of particles here!'
                  stop
                else
                  Current%Constraint = Constraint
                endif
              endif

              Current%MultFromFile = MultFromFile
              Current%Continue     = Continue
             
              !-----------------------------------------------------------------
        endif
     enddo
     nullify(Current)
     return
  end subroutine ReadMomentData


!===============================================================================
! Printing routines
!
!===============================================================================

  subroutine PrintAllMoments()
    !-------------------------------------------------------------------------
    ! Subroutine that uses subroutine PrintMoment to print the information
    ! about all the moments.
    !-------------------------------------------------------------------------
    type(Moment), pointer :: Current => null()
    integer               :: currentl
    real(KIND=dp)         :: ql(3), factor, R
    character(len=1)      :: AX='Z',secAx1='Y', secAx2='Z'

  100 format (16('-'),' Electric Multipole Moments ', 17('-'))
  102 format (60('-'))
    1 format (62('_'))
    2 format (17x,4x, 'Neutrons',8x, 'Protons',9x, 'Total')
    7 format ('Beta_{', 2i2 , '} ', 3(1x,f15.8) )
   71 format ('Beta_{',2x, i2,'} ', 3(1x,f15.8) )
    8 format ('Q_{',i2,'} ',5x, 3(1x,f15.4))
   10 format ('Quantisation Axis             : ', a1)
   11 format ('  With secondary axis ordering: ', a1, ',', a1)


   ! Print information on the quantisationaxis and secondary axis
   select case(QuantisationAxis)
   case(1)
     Ax = 'X'
     select case(SecondaryAxis)
     case(1)
       secAx1='Y' ; secAx2='Z'
     case(2)
       secAx1='Z' ; secAx2='Y'
     end select
   case(2)
     Ax = 'Y'
     select case(SecondaryAxis)
     case(1)
       secAx1='X' ; secAx2='Z'
     case(2)
       secAx1='Z' ; secAx2='X'
     end select
   case(3)
     Ax = 'Z'
     select case(SecondaryAxis)
     case(1)
       secAx1='X' ; secAx2='Y'
     case(2)
       secAx1='Y' ; secAx2='X'
     end select
   end select

    print 100
    print 10, Ax
    print 11, SecAx1, SecAx2
    print 1
    print 2
    print 1

    !-------------------------------------------------------------------------
    ! Print all moments individually
    Current => Root
    currentl = Current%l
    
    call Current%printMoment(Current)
    do while(associated(Current%Next))
      Current => Current%Next
      !------------------------------------
      !Print a new line when getting new l.
      if(currentl .ne. Current%l) print *
      currentl = Current%l
      call Current%PrintMoment(Current)
    enddo
    print 1
    nullify(Current)
    
    !-------------------------------------------------------------------------
    !Printing Beta_lm deformation parameters
    print 2
    print 1
    Current => Root
    currentl = Current%l
    do while(associated(Current%Next))
      Current => Current%Next
      !-------------------------------------------------------------------------
      !Print a new line when getting new l.
      if(currentl .ne. Current%l) print *
      currentl = Current%l

      if(Current%l.gt.1 ) then
          print 7, Current%l, Current%m,Current%Beta
      endif
    enddo
    nullify(Current)
    print 1
    !---------------------------------------------------------------------------
    ! Printing the total multipole moments Q_l
    print 2
    print 1
    do currentl=1, MaxMoment
      ql = CalculateTotalQl(currentl)
      if(all(ql.eq.0.0_dp)) cycle
      print 8, currentl,ql

      Current => FindMoment(Currentl,0,.false.)
      if(.not.associated(Current)) cycle
    enddo
    print 1
    nullify(Current)
    !-------------------------------------------------------------------------
    !Printing Beta_l deformation parameters
    print 2
    print 1
    nullify(Current)
    do currentl=1, MaxMoment
      R = 1.2_dp  * (neutrons + protons)**(1.0_dp/3.0_dp)
      factor = 4.0_dp * pi /(3.0_dp * (neutrons+ protons) * R**(Currentl))

      ql = CalculateTotalQl(currentl)
      if(all(ql.eq.0.0_dp)) cycle
      print 71, currentl,factor*ql
      Current => FindMoment(Currentl,0,.false.)
      if(.not.associated(Current)) cycle
    enddo
    print 1
    nullify(Current)

    call PrintQuadrupoleAlt
    print 102

    return
  end subroutine PrintAllMoments

  subroutine PrintMoment_electric(ToPrint)
    !---------------------------------------------------------------------------
    ! This subroutine provides the printing of all relevant info of a Moment.
    !---------------------------------------------------------------------------
    ! Special printing rules are provided for
    ! - l = 0 moment => Particle numbers
    ! - l =-2 moment => RMS radii
    !---------------------------------------------------------------------------

    class(Moment),       intent(in) :: ToPrint
    character(len=2)                :: ReIm
      1 format (A2, '  Q_{', 2i2, '}', 3(1x,f15.4) )
      2 format ('Constrained ',  33x, f15.4)
      3 format (' Particles  ',  3(1x,f15.4))
      4 format (' RMS radius ',  3(1x,f15.4))
      5 format (A2, ' La_{',i2,i2,'}',   33x,  f15.4)
      6 format (A2, ' De_{',i2,i2,'}',   33x,  e15.7) 

    select case(ToPrint%l)
    !---------------------------------------------------------------------------
    case(0)
      ! Printing the total number of particles
      print 3, sqrt(4*pi)*ToPrint%Value, sqrt(4*pi)*sum(ToPrint%Value)
    !---------------------------------------------------------------------------
    case(-2)
      ! Printing RMS radii
      print 4, sqrt(ToPrint%Value(1)/Neutrons)                                &
      &      , sqrt(ToPrint%Value(2)/(Protons))                               &
      &      , sqrt(sum(ToPrint%Value)/(Neutrons+Protons))

      if(ToPrint%ConstraintType.ne.0) then
          print 2, sqrt(abs(ToPrint%Constraint/(Neutrons + Protons)))
      endif
    !---------------------------------------------------------------------------
    case DEFAULT
      !All other "normal" multipole moments
      ReIm = 'Re'
      if(ToPrint%Impart) ReIm = 'Im'

      print 1, ReIm, ToPrint%l, ToPrint%m, ToPrint%Value(1), ToPrint%Value(2) &
      &        , Sum(ToPrint%Value)

      if(ToPrint%ConstraintType.ne.0) then
        print 2,  ToPrint%Constraint
        print 6, ReIm, ToPrint%l, Toprint%m, ToPrint%Deviation
        print 5, ReIm, ToPrint%l, Toprint%m, ToPrint%Multiplier
      endif
    end select
    !---------------------------------------------------------------------------
  end subroutine PrintMoment_electric

  subroutine PrintQuadrupoleAlt()
    !---------------------------------------------------------------------------
    ! Prints out the Quadrupole moments in their various representations.
    ! This should be the numbers to compare with EV8/CR8 and EV4.
    !---------------------------------------------------------------------------

    use Densities

    1 format(' Cart. Moments', ' X' , 14x, 'Y', 14x, 'Z')
   11 format(' Cart. N', 2x ,3f15.7)
   12 format(' Cart. P', 2x ,3f15.7)
   13 format(' Cart. T', 2x ,3f15.7)
    
    2 format(' (Q, gamma)   ', ' Q', 14x, 'Gamma')
   21 format(' (Q,g) N', 2x ,3f15.7)
   22 format(' (Q,g) P', 2x ,3f15.7)
   23 format(' (Q,g) T', 2x ,3f15.7)
    
    3 format(' (iq1, iq2)   ', ' iq1', 12x, 'iq2')
   31 format(' iq    N', 2x ,3f15.7)
   32 format(' iq    P', 2x ,3f15.7)
   33 format(' iq    T', 2x ,3f15.7)
   
    4 format('              ', ' X^2', 12x, 'Y^2', 12x, 'Z^2')
   41 format(' X^2_i N', 2x ,3f15.7)
   42 format(' X^2_i P', 2x ,3f15.7)
   43 format(' X^2_i T', 2x ,3f15.7) 

    !real(kind=DP)        :: QAlt(3), GAlt(3)
    real(KIND=dp) :: Qi(3,3)
    integer       :: i,j,k, it

    print 1
    !---------------------------------------------------------------
    !Printing only the diagonal components
    ! Note that these depend on the quantization axis and secondary axis.
    select case(QuantisationAxis)
    case(1)
      select case(SecondaryAxis)
      case(1)
        print 11, QCartesian(3,3,1), QCartesian(1,1,1), QCartesian(2,2,1)
        print 12, QCartesian(3,3,2), QCartesian(1,1,2), QCartesian(2,2,2)
        print 13, QCartesian(3,3,3), QCartesian(1,1,3), QCartesian(2,2,3)
      case(2)
        print 11, QCartesian(3,3,1), QCartesian(2,2,1), QCartesian(1,1,1)
        print 12, QCartesian(3,3,2), QCartesian(2,2,2), QCartesian(1,1,2)
        print 13, QCartesian(3,3,3), QCartesian(2,2,3), QCartesian(1,1,3)
      end select

    case(2)
      select case(SecondaryAxis)
      case(1)
        print 11, QCartesian(1,1,1), QCartesian(3,3,1), QCartesian(2,2,1)
        print 12, QCartesian(1,1,2), QCartesian(3,3,2), QCartesian(2,2,2)
        print 13, QCartesian(1,1,3), QCartesian(3,3,3), QCartesian(2,2,3)
      case(2)
        print 11, QCartesian(2,2,1), QCartesian(3,3,1), QCartesian(1,1,1)
        print 12, QCartesian(2,2,2), QCartesian(3,3,2), QCartesian(1,1,2)
        print 13, QCartesian(2,2,3), QCartesian(3,3,3), QCartesian(1,1,3)
      end select

    case(3)
      select case(SecondaryAxis)
      case(1)
        print 11, QCartesian(1,1,1), QCartesian(2,2,1), QCartesian(3,3,1)
        print 12, QCartesian(1,1,2), QCartesian(2,2,2), QCartesian(3,3,2)
        print 13, QCartesian(1,1,3), QCartesian(2,2,3), QCartesian(3,3,3)
      case(2)
        print 11, QCartesian(2,2,1), QCartesian(1,1,1), QCartesian(3,3,1)
        print 12, QCartesian(2,2,2), QCartesian(1,1,2), QCartesian(3,3,2)
        print 13, QCartesian(2,2,3), QCartesian(1,1,3), QCartesian(3,3,3)
      end select
    end select

  !-----------------------------------------------------------------------------
  !    !Double checking the results (they are not printed)
  !    do i=1,2
  !      QAlt(i) = sqrt(16.0_dp/5.0_dp*pi*(Q20%Value(i)**2 + Q22%Value(i)**2))
  !      GAlt(i) = atan2(sqrt(2.0_dp) * Q22%Value(i), Q20%Value(i))
  !    enddo
  !    QAlt(3) = QAlt(1) + QAlt(2)
  !    GAlt(3) = atan2(sqrt(2.0_dp) * sum(Q22%Value(:)), sum(Q20%Value(:)))
  !-----------------------------------------------------------------------------

    print 2
    !Note that Gamma is represented in radians, but is printed in degrees!
    print 21, Q(1), G(1)* 360.0_dp/(2*pi)!, QAlt(1), GAlt(1)* 360.0_dp/(2*pi)
    print 22, Q(2), G(2)* 360.0_dp/(2*pi)!, QAlt(2), GAlt(2)* 360.0_dp/(2*pi)
    print 23, Q(3), G(3)* 360.0_dp/(2*pi)!, QAlt(3), GAlt(3)* 360.0_dp/(2*pi)

    print 3
    print 31, iq1(1), iq2(1)
    print 32, iq1(2), iq2(2)
    print 33, iq1(3), iq2(3)

    Qi(:,:) = 0.0
    ! The expectation values of X^2, Y^2 and Z^2
    do it=1,2
      do k=1,nz
        do j=1,ny
          do i=1,nx
            Qi(1,it) = Qi(1,it) + meshx(i)**2*D_I_I(i+(j-1)*nx +(k-1)*ny*nx,it)
            Qi(2,it) = Qi(1,it) + meshy(i)**2*D_I_I(i+(j-1)*nx +(k-1)*ny*nx,it)
            Qi(3,it) = Qi(1,it) + meshz(i)**2*D_I_I(i+(j-1)*nx +(k-1)*ny*nx,it)
          enddo
        enddo
      enddo
    enddo
    do i=1,3
      Qi(i,3) = Qi(i,1) + Qi(i,2)
    enddo
    print 4
    print 41, Qi(:,1)
    print 42, Qi(:,2)
    print 43, Qi(:,3)

  end subroutine PrintQuadrupoleAlt

  function CalculateTotalQl(l) result(ql)
    !---------------------------------------------------------------------------
    ! Calculates the current value of Q_{l} for a given value of l.
    ! Q_l = \sqrt{\Sum_{m = -l,..,l} [ < Re Q_{lm} >**2 + < Im Q_{lm}**2 > ] }
    !     = \sqrt{\Sum_{m = 0,..,l} f(m)[ < Re Q_{lm} >**2 + < Im Q_{lm}**2 >]}
    !
    !  where f(0) = 1 and f(m\not=0) = 2.
    !---------------------------------------------------------------------------

    integer, intent(in)   :: l
    type(Moment), pointer :: Current
    real(KIND=dp)         :: ql(3), fm
    integer               :: m
    
    ql = 0.0_dp ; m=0
    Current => FindMoment(l,0,.false.)
    do while(m.lt.l .and. .not.associated(Current))
        m = m+1
        Current => FindMoment(l,m,.false.)
        if(.not.associated(Current)) then
           Current => FindMoment(l,m,.true.)
        endif
    enddo
    if(.not.associated(Current)) then
         return
    endif

    ql(1:2) =     Current%Value**2
    ql(3)   = sum(Current%Value)**2
    do while(associated(Current%Next))
      Current  => Current%Next
      if(Current%l .ne.l) exit

      if(Current%m.ne.0) then
        fm=2
      else
        fm=1
      endif

      ql(1:2) = ql(1:2) + Current%Value**2*fm
      ql(3)   = ql(3)   + sum(Current%Value)**2*fm
    enddo
    nullify(Current)
    ql = sqrt(ql)
  end function CalculateTotalQl

!===============================================================================
! Cutoff business
!===============================================================================

  subroutine RutzCutOff
    !---------------------------------------------------------------------------
    ! This function computes the density cut-off function for the computation of
    ! the multipole moments. Multipole constraints should be computed using a
    ! cut-off function since the a constraint on a multipole operator of order l
    ! adds a potential term to the energy which goes as r^l. There always is a
    ! direction on the deformation landscape which becomes unstable.
    !
    ! The cutoff is defined as:
    !
    !                       1
    !          ------------------------------------
    !          1 + exp[(DeltaR(\vec{r})-radd)/acut]
    !
    ! Traditional values are
    !       radd = 4   fm
    !       acut = 0.4 fm
    !
    ! The definition of DeltaR is somewhat involved: it is the distance from
    ! the meshpoint to a surface for constant density.
    !
    ! In practice the computation of DeltaR(i,j,k) is done as follows:
    !   if(Density(i,j,k).le.Treshold ) then
    !      DeltaR(i,j,k) =   min[|r(i,j,k) - r(i',j',k')|]
    !                    with Density(i',j',k').ge.Treshold
    !   else then
    !      DeltaR(i,j,k) = - min[|r(i,j,k) - r(i',j',k')|]
    !                    with Density(i',j',k').le.Treshold
    !    endif
    ! A good value for Treshold ought to be max(Density)/10.
    !
    ! Everything in this comment is taken from
    !                    K. Rutz et al, Nucl. Phys. A590 (1995) 690.
    !
    !---------------------------------------------------------------------------

    use densities

    real(KIND=dp)  :: Treshold(2), DeltaR(nx,ny,nz), Surface(3,7*nx*ny*nz),X,Y,Z
    real(KIND=dp)  :: InterX,InterY,InterZ, Distance
    integer        :: it,i,j,k,l, T, Sig(nx,ny,nz)
    
    real(KIND=dp), pointer     :: rho_3D(:,:,:,:), cut_3D(:,:,:,:)

    if(.not.allocated(Cutoff)) allocate(Cutoff(nx*ny*nz,2))

    ! 3D representation of D_I_I for ease of coding
    rho_3D(1:nx,1:ny,1:nz,1:2) => D_I_I
    cut_3D(1:nx,1:ny,1:nz,1:2) => Cutoff
  
    do it=1,2
      Surface = 0.0_dp

      !Finding the treshold value. At the moment it is fixed to one tenth
      !of the maximum density.
      Treshold(it) = maxval(rho_3D(:,:,:,it))/10.0_dp

      !Taking a ridiculously large number as starting point
      DeltaR = 1.d12

      !T keeps count of the number of surface points the routine found
      T=0

      ! Sig is a sign that keeps track whether a point is on the inside or
      ! the outside of the equidensity surface.
      where(rho_3D(:,:,:,it) .gt. Treshold(it))
              Sig = - 1
      elsewhere
              Sig =   1
      endwhere

      ! First, we construct the mesh coordinates of the equidensity surface.
      ! To do this we check for all points of the grid if the surface lies
      ! between them and their immediate neighbours.
      ! If this is the case, some linear extrapolation is done and the resulting
      ! X,Y and Z coordinates are saved to Surface.
      do k=1,nz-1
        Z = MeshZ(k)
        do j=1,ny-1
          Y = MeshY(j)
          do i=1,nx-1
           X = MeshX(i)

           !Initialising the interpolated values of the coordinates.
           !This needs to be done in light of the last if in this
           !loop-construction.
           InterX= 0.0_dp
           InterY= 0.0_dp
           InterZ= 0.0_dp

           if( ((rho_3d(i  ,j,k,it).ge.Treshold(it)) .and.                &
           &     (rho_3d(i+1,j,k,it).le.Treshold(it)) ) &
           &  .or. &
           &   ((rho_3d(i  ,j,k,it).le.Treshold(it)) .and.                &
           &    (rho_3d(i+1,j,k,it).ge.Treshold(it)))) then
            !In this case the surface lies somewhere between i and i+1
            InterX=X +                                                         &
            &  dx*(Treshold(it)-rho_3d(i,j,k,it))/                        &
            & (rho_3d(i+1,j,k,it)-rho_3d(i,j,k,it))

            T = T + 1

            Surface(1,T) = InterX
            Surface(2,T) = Y
            Surface(3,T) = Z
           endif

           if( ((rho_3d(i,j  ,k,it).ge.Treshold(it)) .and.                     &
           &    (rho_3d(i,j+1,k,it).le.Treshold(it)) ) &
           &  .or. &
           &   ((rho_3d(i,j  ,k,it).le.Treshold(it)) .and.                     &
           &    (rho_3d(i,j+1,k,it).ge.Treshold(it)))) then
            !In this case the surface lies somewhere between j and j+1
            InterY = Y +                                                       &
            & dx*(Treshold(it)-rho_3d(i,j,k,it))/                              &
            & (rho_3d(i,j+1,k,it)-rho_3d(i,j,k,it))

            T = T + 1

            Surface(1,T) = X
            Surface(2,T) = InterY
            Surface(3,T) = Z
           endif

           if( ((rho_3d(i,j,k  ,it).ge.Treshold(it)) .and.                     &
           &    (rho_3d(i,j,k+1,it).le.Treshold(it)))                          &
           &  .or. &
           &   ((rho_3d(i,j,k  ,it).le.Treshold(it)) .and.                     &
           &   (rho_3d(i,j,k+1,it).ge.Treshold(it)) ) ) then
            !In this case the surface lies somewhere between k and k+1
            InterZ = Z +                                                       &
            & dx*(Treshold(it)-rho_3d(i,j,k,it))/                              &
            & (rho_3d(i,j,k+1,it) - rho_3d(i,j,k,it))
            T = T + 1
            Surface(1,T) = X
            Surface(2,T) = Y
            Surface(3,T) = InterZ
           endif
          enddo
        enddo
      enddo

      ! Now we can find the minimum distance from every point on the
      ! mesh to the surface.
      do k=1,nz
        Z = MeshZ(k)
        do j=1,ny
          Y = MeshY(j)
          do i=1,nx
            X = MeshX(i)
            do l=1,T
              !Distance to the surface point
              Distance = (X - Surface(1,l))**2 + (Y -Surface(2,l))**2 +        &
              &          (Z - Surface(3,l))**2
              DeltaR(i,j,k) = min(DeltaR(i,j,k) , Distance)
            enddo
            DeltaR(i,j,k) = Sig(i,j,k)*sqrt(DeltaR(i,j,k) )
          enddo
        enddo
      enddo

      ! With this distance we can calculate the cutoff function.
      Cut_3D(:,:,:,it) = 1.0d0/(1.0d0 + exp( (DeltaR - radd)/acut)  )
    enddo
    return
  end subroutine RutzCutOff

  subroutine StandardCutoff
    !---------------------------------------------------------------------------
    ! This subroutine calculates a cutoff function in a density independent way.
    !        exp(-d)/(1+exp(-d))  if d > 0
    ! cutoff(r) =
    !         1 /(1+exp(d))        if d < 0
    ! with d = (|r| - radd)/acut
    !
    !---------------------------------------------------------------------------

    real(kind=dp) :: X,Y,Z,d
    integer :: i,j,k
    real(KIND=dp), pointer     :: cut_3D(:,:,:,:)

    if(.not.allocated(Cutoff)) allocate(Cutoff(nx*ny*nz,2))
    cut_3D(1:nx,1:ny,1:nz,1:2) => Cutoff
    
    do k=1,nz
      Z = MeshZ(k)
      do j=1,ny
        Y = MeshY(j)
        do i=1,nx
          X = MeshX(i)
          d = (sqrt(X**2 + Y**2 + Z**2) - radd)/acut
          if( d .ge. 0.0d0) then
            Cut_3D(i,j,k,:) = exp(-d)/(1 + exp(-d))
          else
            Cut_3D(i,j,k,:) = 1.0d0/(1 + exp(d))
          endif
        enddo
      enddo
    enddo

  end subroutine StandardCutoff

!===============================================================================
! Read/write moments from file
!===============================================================================
  subroutine ReadMoment(IChan, ioerror)
    !---------------------------------------------------------------------------
    ! Subroutine to read information on a multipole moment from the 
    ! next line. 
    !---------------------------------------------------------------------------
    integer, intent(in)    :: IChan
    integer, intent(inout) :: ioerror

    type (Moment), pointer :: Mom

    integer                :: l,m, ConStraintType
    real(KIND=dp)          :: Value(2), Intensity, Constraint, Multiplier 
    real(KIND=dp)          :: deviation
    logical                :: impart

    read(IChan, iostat=ioerror) l,m,impart, ConstraintType, Value,Constraint,  &
    &                           Deviation,Multiplier,Intensity
    if(ioerror.ne.0) return
    !---------------------------------------------------------------------------
    ! Finding moment.
    Mom => FindMoment(l,m,Impart)
    !---------------------------------------------------------------------------
    ! Assigning correct values
   
    if(ContinueAll  .or. mom%continue) then    
      Mom%ConstraintType = ConstraintType
      Mom%Value          = Value    
    
      Mom%Constraint     = Constraint
      Mom%Intensity      = Intensity
    endif
  
    if(Mom%multfromfile .or. ContinueAll) then        
      Mom%Multiplier     = Multiplier
    endif
  end subroutine ReadMoment

  subroutine WriteMoment(Mom,Ochan)
    !---------------------------------------------------------------------------
    ! Subroutine that writes all relevant values of multipole moment to file.
    !---------------------------------------------------------------------------
    class(Moment), intent(in) :: Mom
    integer, intent(in)       :: Ochan
    integer                   :: io

    io = 0
    write(OChan)                Mom%l,Mom%m,Mom%Impart, Mom%constrainttype,  &
    &                           Mom%value, Mom%constraint,Mom%deviation,     &
    &                           Mom%multiplier, Mom%Intensity       
    
if(io.ne.0) call stp('Error while writing multipole moment to file!')
  end subroutine WriteMoment


!===============================================================================
! Various things
!===============================================================================

  subroutine TurnOffConstraints(iter)
    !---------------------------------------------------------------------------
    ! Checks all of the constraints for temporary ones and 
    ! sees if they have reached their expiration iteration number.
    !---------------------------------------------------------------------------
    integer, intent(in)   :: iter
    type(Moment), pointer :: Current

    1 format ('Turning of constraint on multipole moment.')
    2 format (' ' , a2 , ' l = ', i2, ' m = ', i2)
    3 format ('after ', i4, ' iterations.') 
    4 format ('------------------------------------------')

    Current => root

    do while(associated(Current%next))
            Current => Current%next
            if(Current%ConstraintType .eq. 0) cycle
    if(Current%iteration      .le. 0) cycle
            if(iter                   .gt. Current%iteration) then
                    Current%Constrainttype=0
                    print 4
                    print 1
                    if(Current%Impart) then
                            print 2, 'Im', current%l, current%m
                    else
                            print 2, 'Re', current%l, current%m
                            print 3, iter
                    endif
                    print 4
            endif
    enddo
  end subroutine TurnOffConstraints

  function checkconstraints() result(projectpresent)
    !---------------------------------------------------------------------------
    ! Check all moments for constrainttype == 2.
    !---------------------------------------------------------------------------
    
    logical :: projectpresent
    type(Moment), pointer :: current

    projectpresent = .false.
    Current => Root
    do while(associated(Current%next))
        Current => Current%Next
        if(Current%constrainttype .eq. 2) then
            projectpresent = .true.
            return
        endif
    enddo

  end function checkconstraints

  recursive function FindMoment(l,m,Impart,StartMoment) result(FoundMoment)
    !---------------------------------------------------------------------------
    ! Subroutine that finds a pointer to the moment, specified by multipole
    ! values l,m and whether it is a real or imaginary part.
    ! For maximum efficiency, it is possible to specify a StartMoment, so that
    ! the search starts at that specific moment.
    ! Ex: Tantalus can find Im(Q_{22}) faster if it starts from Re(Q_{20}).
    !
    ! The result is null if the moment isn't found.
    !---------------------------------------------------------------------------
    integer, intent(in)                        :: l,m
    logical, intent(in)                        :: Impart
    type(Moment), intent(in), pointer, optional:: StartMoment
    type(Moment), pointer                      :: Current, FoundMoment

    nullify(Current); nullify(FoundMoment)

    if(present(StartMoment)) then
      Current => StartMoment
    else
      Current => Root
    endif

    if((Current%l.eq.l) .and. (Current%m .eq. m) .and.                       &
      &               (Impart.eqv.Current%Impart)) then
        !Then we've found the correct moment.
        FoundMoment => Current
        return
    endif

    do while(associated(Current%Next))
      Current => Current%Next
      if((Current%l.eq.l) .and. (Current%m .eq. m) .and.                       &
      &               (Impart.eqv.Current%Impart)) then
        !Then we've found the correct moment.
        FoundMoment => Current
        return
      endif
    enddo
    if(present(StartMoment)) then
      ! If this part of the code gets reached, we picked a bad starting point.
      ! So we start over again!
      FoundMoment => FindMoment(l,m,Impart)
    else
      FoundMoment => null()
    endif
    return
  end function FindMoment

  subroutine clean_moments

    if(allocated(Constraint_I_I)) deallocate(Constraint_I_I)
    if(allocated(Cutoff))         deallocate(Cutoff)
    nullify(Root)

  end subroutine clean_moments
!===============================================================================
!
!===============================================================================
end module 
