module parameterization
 !==============================================================================
 !_________ _______  _       _________ _______  _                 _______ 
 !\__   __/(  ___  )( (    /|\__   __/(  ___  )( \      |\     /|(  ____ \
 !   ) (   | (   ) ||  \  ( |   ) (   | (   ) || (      | )   ( || (    \/
 !   | |   | (___) ||   \ | |   | |   | (___) || |      | |   | || (_____ 
 !   | |   |  ___  || (\ \) |   | |   |  ___  || |      | |   | |(_____  )
 !   | |   | (   ) || | \   |   | |   | (   ) || |      | |   | |      ) |
 !   | |   | )   ( || )  \  |   | |   | )   ( || (____/\| (___) |/\____) |
 !   )_(   |/     \||/    )_)   )_(   |/     \|(_______/(_______)\_______)
 !                                                                       
 !  Copyright W. Ryssens & M. Bender
 !
 !==============================================================================
 
 use compilation
 use geninfo
 
 implicit none
    
    !---------------------------------------------------------------------------
    ! Automatically generated parameters of the parameterization
$PARAMDECL
    !---------------------------------------------------------------------------
    ! Constants that enter the game, together with the e2 from the Coulomb
    ! module.
    !---------------------------------------------------------------------------
    real(KIND=dp) :: hbm(2)         = 20.73551910_dp 
    real(KIND=dp) :: nucleonmass(2) = (/939.565379_dp , 938.272046_dp /)
    !---------------------------------------------------------------------------  
    ! Treatment of the one-body COM correction.
    ! (0) not included
    ! (1) perturbatively included
    ! (2) completely included
    integer       :: COM1body = 2
    !------------------------------------------------------------------------------
    ! Temporary integer, whether or not coulomb is added
    integer, public :: coultreatment = 1
    !---------------------------------------------------------------------------
    ! Value of the electron charge, squared
    real(KIND=dp) :: e2 =1.43996446_dp 

contains
    
   subroutine readparameterization(name_param, func_name) 
    !---------------------------------------------------------------------------
    ! Read the parameterization information from the .param file.
    
    character(len=20) :: name, func_file
    character(len=*), intent(in) :: name_param, func_name
    integer           :: io
    
    ! predefined options
    namelist /skf/ name, func_file, hbm, e2, COM1body, coultreatment, &
    ! Those generated by Hephaestos
    & $READPARAMS                        
  
    open(unit=12, file='forces.param',iostat=io)

    if (io.ne.0) then
      print *, "Can't open forces.param!"
      print *, 'iostat = ', io
      stop
    endif
    
    read (unit=12, nml=skf)                   ! Read the parameterization info
    close(unit=12)
        
    name = to_upper(name)  ; func_file = to_upper(func_file)

    !---------------------------------------------------------------------------
    ! Some sanity checks
    if(adjustl(func_file) .ne. adjustl(func_name)) then
        print *, '============================================================='
        print *, ' .func file used for compilation      = ', adjustl(func_name)
        print *, ' .func file for this parameterization = ', adjustl(func_file)
        print *, '============================================================='
        stop
    endif 
    
    if(adjustl(name_param) .ne. adjustl(name)) then
        print *, '============================================================='
        print *, ' .param asked for = ', adjustl(name_param)
        print *, ' .param read      = ', adjustl(name)
        print *, '============================================================='
        stop
    endif 
    
    !---------------------------------------------------------------------------
    ! Checking that all requested parameters have been read.
    
  end subroutine readparameterization
  !=============================================================================
  ! Various functions that might be useful to define coupling constants in 
  ! the .func files.
  !=============================================================================
  
  real(KIND=dp) function Cc(t,x,p,s,it) result(c)
    !---------------------------------------------------------------------------
    ! Michaels convention for coupling coefficients of central Skyrme terms.
    ! 
    !
    ! C^+/-_cST       +              -
    !              t      tx      t    tx
    !       
    !    c00     +3/8     0     +5/8  +1/2 
    !    c01     -1/8   -1/4    +1/8  +1/4
    !    c10     -1/8   +1/4    +1/8  +1/4
    !    c11     -1/8     0     +1/8   0
    !---------------------------------------------------------------------------
    
    integer, intent(in)      :: p,s,it
    real(KIND=dp),intent(in) :: t,x
    
    c = 0
    
    select case(p)
    !---------------------------------------------------------------------------
    case(+1) ! C^+_c
      select case(s)          ! C^+_cS  
        case(0)               ! C^+_c0 
          select case(it)     ! C^+_c0T
          case(0)
            c = +3.0/8.0 * t                     ! C^+_c00
          case(1)
            c = -1.0/8.0 * t  - 1.0/4.0 * t * x  ! C^+_c01 
          end select
        case(1)               ! C^+_c1 
          select case(it)     ! C^+_c1T
          case(0)
            c = -1.0/8.0 * t  + 1.0/4.0 * t * x  ! C^+_c10
          case(+1)
            c = -1.0/8.0 * t                     ! C^+_c11
          end select
      end select
    !---------------------------------------------------------------------------
    case(-1) ! C^-_c
      select case(s)          ! C^-_cS  
        case(0)               ! C^-_c0 
          select case(it)     ! C^-_c0T
          case(0)
            c = +5.0/8.0 * t  + 1.0/2.0 * t * x  ! C^-_c00
          case(1)
            c = +1.0/8.0 * t  + 1.0/4.0 * t * x  ! C^-_c01 
          end select
        case(1)               ! C^-_c1 
          select case(it)     ! C^-_c1T
          case(0)
            c = +1.0/8.0 * t  + 1.0/4.0 * t * x  ! C^-_c10
          case(+1)
            c = +1.0/8.0 * t                     ! C^-_c11
          end select
      end select
    end select
    !---------------------------------------------------------------------------
  end function Cc


end module parameterization
