module parameterization
 !==============================================================================
 !_________ _______  _       _________ _______  _                 _______ 
 !\__   __/(  ___  )( (    /|\__   __/(  ___  )( \      |\     /|(  ____ \
 !   ) (   | (   ) ||  \  ( |   ) (   | (   ) || (      | )   ( || (    \/
 !   | |   | (___) ||   \ | |   | |   | (___) || |      | |   | || (_____ 
 !   | |   |  ___  || (\ \) |   | |   |  ___  || |      | |   | |(_____  )
 !   | |   | (   ) || | \   |   | |   | (   ) || |      | |   | |      ) |
 !   | |   | )   ( || )  \  |   | |   | )   ( || (____/\| (___) |/\____) |
 !   )_(   |/     \||/    )_)   )_(   |/     \|(_______/(_______)\_______)
 !                                                                       
 !  Copyright W. Ryssens & M. Bender
 !
 !==============================================================================
 
 use compilation
 use geninfo
 
 implicit none
    
    !---------------------------------------------------------------------------
    ! Automatically generated parameters of the parameterization
$PARAMDECL
    !---------------------------------------------------------------------------
    ! Constants that enter the game, together with the e2 from the Coulomb
    ! module.
    !---------------------------------------------------------------------------
    real(KIND=dp) :: hbm(2)         = 20.73551910_dp 
    real(KIND=dp) :: nucleonmass(2) = (/939.565379_dp , 938.272046_dp /)

    !---------------------------------------------------------------------------  
    ! Treatment of the one-body COM correction.
    ! (0) not included
    ! (1) perturbatively included
    ! (2) completely included
    integer       :: COM1body = 2
    integer       :: COM2body = 0
    !------------------------------------------------------------------------------
    ! Temporary integer, whether or not coulomb is added
    integer       :: coultreatment = 1
    
    !---------------------------------------------------------------------------
    ! Value of the electron charge, squared
    real(KIND=dp) :: e2 =1.43996446_dp 
    !------------------------------------------------------------------------------
    ! Effective size of the proton to take into account. 
    ! The proton density is folded with a Gaussian
    !   G(|r1 - r2|) = (r0 * sqrt(pi))**(-1) * exp[-(r/r0)**2]
    ! If r0 = 0, this is a delta-function and no folding is performed.
    real(KIND=dp) :: protonsize = 0.0

contains
    
   subroutine readparameterization(name_param, func_name) 
    !---------------------------------------------------------------------------
    ! Read the parameterization information from the .param file.
    
    character(len=20) :: name, func_file
    character(len=*), intent(in) :: name_param, func_name
    integer           :: io
    
    ! predefined options
    namelist /skf/ name, func_file, hbm, e2, COM1body, COM2body, coultreatment,&
    &              protonsize,                                                 &
    ! Those generated by Hephaestos
    & $READPARAMS                        
  
    open(unit=12, file='forces.param',iostat=io)

    if (io.ne.0) then
      print *, "Can't open forces.param!"
      print *, 'iostat = ', io
      stop
    endif
    
    read (unit=12, nml=skf)                     ! Read the parameterization info
    close(unit=12)
        
    name = to_upper(name)  ; func_file = to_upper(func_file)

    !---------------------------------------------------------------------------
    ! Some sanity checks
    if(adjustl(func_file) .ne. adjustl(func_name)) then
        print *, '============================================================='
        print *, ' .func file used for compilation      = ', adjustl(func_name)
        print *, ' .func file for this parameterization = ', adjustl(func_file)
        print *, '============================================================='
        stop
    endif 
    
    if(adjustl(name_param) .ne. adjustl(name)) then
        print *, '============================================================='
        print *, ' .param asked for = ', adjustl(name_param)
        print *, ' .param read      = ', adjustl(name)
        print *, '============================================================='
        stop
    endif 
    
    !---------------------------------------------------------------------------
    ! Checking that all requested parameters have been read.
    ! Hephaestos generates a list of 'ifs' that check if the parameters are
    ! exactly their initializer
$CHECKPARAMS
    
  end subroutine readparameterization
  
  subroutine printparameterization(param_name, func_name)
    !---------------------------------------------------------------------------
    ! Printing the available information on the parameterization/functional.
    !
    !---------------------------------------------------------------------------
    character(len=*), intent(in) :: param_name, func_name
    
    1 format (80('-'))
    2 format (' Parameterization name',  5x, 20a)
    3 format (' Functional name      ',  5x, 20a)
    4 format (' - - - - - - - - - - -')
    5 format (' Parameters' )
    
    ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    
    7  format (' Coulomb Treatment = ', i2)
    70 format ('   No direct, nor exchange energy.')
    71 format ('   Direct and exchange included.')
    72 format ('   Only Direct contribution included.') 
  
    8  format ('   Protonsize = ', f5.3 )
    81 format ('   Charge density folded.')
    ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    
    9  format (' Center-of-mass options')
    93 format ('   One-body: self-consistent')
    92 format ('   One-body: perturbative')
    91 format ('   One-body: not included')
    96 format ('   Two-body: self-consistent')
    95 format ('   Two-body: perturbative')
    94 format ('   Two-body: not included')
    ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    
    100 format( ' Elementary Constants')
    101 format(" e^2            = ", f11.8 ,' (sqrt(MeV fm)) ')
    102 format(" hbar^2/(2*mn)  = ", f11.8 ,' (MeV fm^2)'&
    &           ,/," hbar^2/(2*mp)  = ", f11.8 ,' (MeV fm^2)')
    
    print 1
    print 2, adjustl(param_name)
    print 3, adjustl(func_name)
    print 4
    print 5
    
$PRINTPARAMS
    
    print 4
    
    ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    
    ! All coulomb options
    print 7, coultreatment
    select case(Coultreatment)
    case(0)
      print 70
    case(1)
      print 71
    case(2)
      print 72
    end select 
    
    print 8, protonsize
    if(protonsize.ne.0.0) then
      print 81
    endif
    ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    
    print 4
    print 9
    select case (COM1body)
    case(0)
      print 91
    case(1)
      print 92
    case(2)
      print 93
    end select
    select case (COM2body)
    case(0)
      print 94
    case(1)
      print 95
    case(2)
      print 96
      stop
    end select
    ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -    
    ! Constants
    print 4
    print 100
    print 101, e2
    print 102, hbm
    
  end subroutine printparameterization
  
  !=============================================================================
  ! Various functions that might be useful to define coupling constants in 
  ! the .func files.
  !=============================================================================
  
  real(KIND=dp) function Cc(t,x,p,s,it) result(c)
    !---------------------------------------------------------------------------
    ! Michaels convention for coupling coefficients of central Skyrme terms.
    ! 
    !
    ! C^+/-_cST       +              -
    !              t      tx      t    tx
    !       
    !    c00     +3/8     0     +5/8  +1/2 
    !    c01     -1/8   -1/4    +1/8  +1/4
    !    c10     -1/8   +1/4    +1/8  +1/4
    !    c11     -1/8     0     +1/8   0
    !---------------------------------------------------------------------------
    
    integer, intent(in)      :: p,s,it
    real(KIND=dp),intent(in) :: t,x
    
    c = 0
    
    select case(p)
    !---------------------------------------------------------------------------
    case(+1) ! C^+_c
      select case(s)          ! C^+_cS  
        case(0)               ! C^+_c0 
          select case(it)     ! C^+_c0T
          case(0)
            c = +3.0/8.0 * t                     ! C^+_c00
          case(1)
            c = -1.0/8.0 * t  - 1.0/4.0 * t * x  ! C^+_c01 
          end select
        case(1)               ! C^+_c1 
          select case(it)     ! C^+_c1T
          case(0)
            c = -1.0/8.0 * t  + 1.0/4.0 * t * x  ! C^+_c10
          case(+1)
            c = -1.0/8.0 * t                     ! C^+_c11
          end select
      end select
    !---------------------------------------------------------------------------
    case(-1) ! C^-_c
      select case(s)          ! C^-_cS  
        case(0)               ! C^-_c0 
          select case(it)     ! C^-_c0T
          case(0)
            c = +5.0/8.0 * t  + 1.0/2.0 * t * x  ! C^-_c00
          case(1)
            c = +1.0/8.0 * t  + 1.0/4.0 * t * x  ! C^-_c01 
          end select
        case(1)               ! C^-_c1 
          select case(it)     ! C^-_c1T
          case(0)
            c = +1.0/8.0 * t  + 1.0/4.0 * t * x  ! C^-_c10
          case(+1)
            c = +1.0/8.0 * t                     ! C^-_c11
          end select
      end select
    end select
    !---------------------------------------------------------------------------
  end function Cc


end module parameterization
