module sphericalharmonics
!===============================================================================
!  #######   ##   #    # #####   ##   #      #    #  ####
!     #     #  #  ##   #   #    #  #  #      #    # #
!     #    #    # # #  #   #   #    # #      #    #  ####
!     #    ###### #  # #   #   ###### #      #    #      #
!     #    #    # #   ##   #   #    # #      #    # #    #
!     #    #    # #    #   #   #    # ######  ####   ####
!
!  Copyright W. Ryssens & M. Bender
!
!===============================================================================
! The representation of the spherical harmonics used is the one from Messiah,
! using real spherical harmonics.
!
! Thus the spherical harmonics are, in terms of spherical coordinates:
!
!        Y_{l}^{m} = (-1)^{m}[(2*l+1)/4\pi (l-m)!/(l+m)!]^{1/2}
!                 *    P^{m}_{l}(cos(\theta)) e^{i m \phi}
!
!  where the P^{m}_{l} are the associated Legendre Polynomials and -l <= m <= l.
!  These polynomials can be generated by recursion.
!
! The code "talks" about the real and imaginary parts of these moments.
! The only relevant values of m are thus positive.
!
!   Re Y_lm =  1/2 * (Y_l+m + Y_l-m)
!   Im Y_lm = -i/2 * (Y_l+m - Y_l-m)
!
!===============================================================================
 use geninfo

 implicit none
 
contains

   subroutine GenSphericalHarmonics(maxmoment,mx,my,mz,                        &
   &                                meshx,meshy,meshz, SpherHarmMesh,          &
   &                                quantisationaxis,secondaryaxis)
    !---------------------------------------------------------------------------
    ! This function computes the values of all the spherical harmonics up to
    ! l=Maxmoment where Mesh supplies the values of the x/y/z coordinates.
    ! 
    ! On output, SpherHarmMesh contains the values of the spherical harmonics
    ! at the mesh points. These are quantized according to the choices made
    ! for QuantisationAxis and SecondaryAxis.
    !---------------------------------------------------------------------------
    ! The formula used is the one from Messiah:
    !    Y^{m}_{l} = (-1)^m [(2*l+1)/(4*\pi) (l-m)!/(l+m)!]^{1/2}
    !              *  P^m_{l}[cos(\theta)] e^{im\phi}
    !
    ! Translating this formula into Cartesian coordinates is also highly
    ! dependent on the values for QuantisationAxis and SecondaryAxis.
    ! See explanation in the moments module.
    !---------------------------------------------------------------------------

    integer, intent(in)        :: mx,my,mz, maxmoment
    integer, intent(in)        :: quantisationaxis,secondaryaxis
    real(KIND=dp), intent(in)  :: meshx(mx), meshy(my), meshz(mz)

    real(KIND=dp)  :: LegendreMesh (mx,my,mz,0:MaxMoment,0:MaxMoment)
    real(KIND=dp)  :: SpherHarmMesh(mx,my,mz,0:MaxMoment,0:MaxMoment,2)
    !r, Sin(\theta),Cos(\theta),\phi, sin(m*\Phi) and cos(m*\Phi)
    real(KIND=dp)  :: r,cosTheta,sinTheta, phi,sinmPhi, cosmPhi
    real(KIND=dp)  :: fac, X,Y,Z
    integer        :: i,j,k,l,m,q
    real(KIND=dp)  :: factorialquotient

    do k=1,mz
      do j=1,my
        do i=1,mx
          X = MeshX(i)
          Y = MeshY(j)
          Z = MeshZ(k)

          r        =sqrt(X**2+Y**2+Z**2)
          phi      =0
          select case(QuantisationAxis)
          case(1)
                ! QuantisationAxis = X
                ! Meaning the angle theta is with reference to X-direction
                sinTheta =sqrt(Z**2+Y**2)/r
                cosTheta =X/r

                select case(SecondaryAxis)
                case(1)
                  phi      =atan2(Z,Y)
                case(2)
                  phi      =atan2(Y,Z)
                end select
          case(2)
                ! QuantisationAxis = Y
                ! Meaning the angle theta is with reference to Y-direction
                sinTheta =sqrt(X**2+Z**2)/r
                cosTheta =Y/r

                select case(SecondaryAxis)
                case(1)
                  phi      =atan2(Z,X)
                case(2)
                  phi      =atan2(X,Z)
                end select
          case(3)
                ! QuantisationAxis = Z
                ! Meaning the angle theta is with reference to Z-direction
                sinTheta =sqrt(X**2+Y**2)/r
                cosTheta =Z/r

                select case(SecondaryAxis)
                case(1)
                  phi      =atan2(Y,X)
                case(2)
                  phi      =atan2(X,Y)
                end select
          case DEFAULT
                stop('Quantisationaxis is not valid in GenSphericalHarmonics.')
          end select

          !Calculating the values of the spherical harmonics
          do m=0,MaxMoment
            ! Finding the associated Legendre Polynomials
            LegendreMesh(i,j,k,:,m)=legendre_pnm(MaxMoment, m, cosTheta)
            sinmPhi=sin(m*Phi)
            cosmPhi=cos(m*Phi)

            do l=m,MaxMoment ! Note that l>= m
              factorialquotient=1.0_dp
              do q=1,2*m
                factorialquotient = factorialquotient/( l + m - q + 1)
              enddo

              fac=(-1)**m*sqrt(factorialquotient)*r**l
              fac = fac * sqrt((2*l +1)/(4 * pi))
              ! Real part of Y_{lm}
              SpherHarmMesh(i,j,k,l,m,1)=fac*LegendreMesh(i,j,k,l,m)*cosmPhi
              ! Imaginary part of Y_{lm}
              SpherHarmMesh(i,j,k,l,m,2)=fac*LegendreMesh(i,j,k,l,m)*sinmPhi
            enddo
          enddo
        enddo
      enddo
    enddo

 end subroutine GenSphericalHarmonics

 function legendre_pnm ( n, m, x ) result(cx)
      !-------------------------------------------------------------------------
      ! Taken on 14/05/13 from
      !    http://people.sc.fsu.edu/~jburkardt/f_src/polpak/polpak.html
      ! Under the GNU LGPL licence, which can be found at
      !    http://www.gnu.org/licenses/gpl.html
      !
      ! Minor changes from the original version:
      !    - double precision instead of single precision
      !    - changed from subroutine to function, for clarity and ease of use
      !*************************************************************************
      !
      ! LEGENDRE_PNM evaluates the associated Legendre polynomial Pnm(x) of the 
      !first kind.
      !
      !
      !  Differential equation:
      !
      !    (1-X*X) * Y'' - 2 * X * Y + ( N (N+1) - (M*M/(1-X*X)) * Y = 0
      !
      !  First terms:
      !
      !    M = 0  ( = Legendre polynomials of first kind P(N)(X) )
      !
      !    P00 =    1
      !    P10 =    1 X
      !    P20 = (  3 X**2 -   1)/2
      !    P30 = (  5 X**3 -   3 X)/2
      !    P40 = ( 35 X**4 -  30 X**2 +   3)/8
      !    P50 = ( 63 X**5 -  70 X**3 +  15 X)/8
      !    P60 = (231 X**6 - 315 X**4 + 105 X**2 -  5)/16
      !    P70 = (429 X**7 - 693 X**5 + 315 X**3 - 35 X)/16
      !
      !    M = 1
      !
      !    P01 =   0
      !    P11 =   1 * SQRT(1-X*X)
      !    P21 =   3 * SQRT(1-X*X) * X
      !    P31 = 1.5 * SQRT(1-X*X) * (5*X*X-1)
      !    P41 = 2.5 * SQRT(1-X*X) * (7*X*X*X-3*X)
      !
      !    M = 2
      !
      !    P02 =   0
      !    P12 =   0
      !    P22 =   3 * (1-X*X)
      !    P32 =  15 * (1-X*X) * X
      !    P42 = 7.5 * (1-X*X) * (7*X*X-1)
      !
      !    M = 3
      !
      !    P03 =   0
      !    P13 =   0
      !    P23 =   0
      !    P33 =  15 * (1-X*X)**1.5
      !    P43 = 105 * (1-X*X)**1.5 * X
      !
      !    M = 4
      !
      !    P04 =   0
      !    P14 =   0
      !    P24 =   0
      !    P34 =   0
      !    P44 = 105 * (1-X*X)**2
      !
      !  Recursion:
      !
      !    if N < M:
      !      P(N,M) = 0
      !    if N = M:
      !      P(N,M) = (2*M-1)!! * (1-X*X)**(M/2) where N!! means the product of
      !      all the odd integers less than or equal to N.
      !    if N = M+1:
      !      P(N,M) = X*(2*M+1)*P(M,M)
      !    if N > M+1:
      !      P(N,M) = ( X*(2*N-1)*P(N-1,M) - (N+M-1)*P(N-2,M) )/(N-M)
      !
      !  Restrictions:
      !
      !    -1 <= X <= 1
      !     0 <= M <= N
      !
      !  Special values:
      !
      !    P(N,0)(X) = P(N)(X), that is, for M=0, the associated Legendre
      !    polynomial of the first kind equals the Legendre polynomial of the
      !    first kind.
      !
      !  Modified:
      !
      !    24 June 2001
      !
      !  Author:
      !
      !    John Burkardt
      !
      !  Parameters:
      !
      !    Input, integer N, the maximum first index of the Legendre
      !    polynomial, which must be at least 0.
      !
      !    Input, integer M, the second index of the Legendre polynomial,
      !    which must be at least 0, and no greater than N.
      !
      !    Input, real X, the point at which the polynomial is to be
      !    evaluated.  X must satisfy -1 <= X <= 1.
      !
      !    Output, real CX(0:N), the values of the first N+1 polynomials.
      !-------------------------------------------------------------------------
      implicit none

      real(KIND=dp)    :: cx(0:n)
      real(KIND=dp)     :: fact, somx2
      real(KIND=dp),  intent(in) :: x
      integer, intent(in) :: m,n
      integer :: i

      if ( m < 0 ) then
      write ( *, '(a)' ) ' '
      write ( *, '(a)' ) 'LEGENDRE_PNM - Fatal error!'
      write ( *, '(a,i6)' ) '  Input value of M is ', m
      write ( *, '(a)' ) '  but M must be nonnegative.'
      stop
      end if

      if ( m > n ) then
      write ( *, '(a)' ) ' '
      write ( *, '(a)' ) 'LEGENDRE_PNM - Fatal error!'
      write ( *, '(a,i6)' ) '  Input value of M = ', m
      write ( *, '(a,i6)' ) '  Input value of N = ', n
      write ( *, '(a)' ) '  but M must be less than or equal to N.'
      stop
      end if

      if ( x < -1.0E+00 ) then
      write ( *, '(a)' ) ' '
      write ( *, '(a)' ) 'LEGENDRE_PNM - Fatal error!'
      write ( *, '(a,g14.6)' ) '  Input value of X = ', x
      write ( *, '(a)' ) '  but X must be no less than -1.'
      stop
      end if

      if ( x > 1.0E+00 ) then
      write ( *, '(a)' ) ' '
      write ( *, '(a)' ) 'LEGENDRE_PNM - Fatal error!'
      write ( *, '(a,g14.6)' ) '  Input value of X = ', x
      write ( *, '(a)' ) '  but X must be no more than 1.'
      stop
      end if

      cx(0:m-1) = 0.0E+00

      cx(m) = 1.0E+00
      somx2 = sqrt ( 1.0E+00 - x**2 )

      fact = 1.0E+00
      do i = 1, m
          cx(m) = - cx(m) * fact * somx2
          fact = fact + 2.0E+00
      end do

      if ( m == n ) then
          return
      end if

      cx(m+1) = x * real ( 2 * m + 1 ) * cx(m)

      do i = m+2, n
          cx(i) = ( real ( 2 * i - 1 ) * x * cx(i-1) &
          - real ( i + m - 1 ) * cx(i-2) ) / real ( i - m )
      end do

      return
  end function Legendre_pnm


end module sphericalharmonics
