!===============================================================================
!     __  __  ___   ____ ____
!    |  \/  |/ _ \ / ___/ ___|__ _
!    | |\/| | | | | |  | |   / _` |
!    | |  | | |_| | |__| |__| (_| |
!    |_|  |_|\___/ \____\____\__,_|
!
!    Copyright (C) 2026 W. Ryssens and M. Bender
!
!    This program is free software: you can redistribute it and/or modify
!    it under the terms of the GNU Affero General Public License as published
!    by the Free Software Foundation, either version 3 of the License, or
!    (at your option) any later version.
!
!    This program is distributed in the hope that it will be useful,
!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!    GNU Affero General Public License for more details.
!
!    You should have received a copy of the GNU Affero General Public License
!    along with this program.  If not, see <https://www.gnu.org/licenses/>.
!
!===============================================================================
module sphericalharmonics
!===============================================================================
! The representation of the spherical harmonics used is the one from Messiah,
! using real spherical harmonics.
!
! Thus the spherical harmonics are, in terms of spherical coordinates:
!
!        Y_{l}^{m} = (-1)^{m}[(2*l+1)/4\pi (l-m)!/(l+m)!]^{1/2}
!                 *    P^{m}_{l}(cos(\theta)) e^{i m \phi}
!
!  where the P^{m}_{l} are the associated Legendre Polynomials and -l <= m <= l.
!  These polynomials can be generated by recursion.
!
! The code "talks" about the real and imaginary parts of these moments.
! The only relevant values of m are thus positive.
!
!   Re Y_lm =  1/2 * (Y_l+m + Y_l-m)
!   Im Y_lm = -i/2 * (Y_l+m - Y_l-m)
!
!===============================================================================
 use geninfo

 implicit none
 
contains

   function figure_out_multipole_moments(sx,sy,sz,maxmoment,&
   &                                        quantisation_axis,secondary_axis) &
   &   result(moment_list)
    !----------------------------------------------------------------------------
    ! This routine determines what multipole moments of a function with specific
    ! symmetry properties do not vanish. 
    ! 
    ! Phrased differently: if a function f has symmetry signature (sx,sy,sz), for
    ! what values of l and m does the integral
    ! 
    !      int d^3r f(r) Q_{lm}(r)
    ! 
    ! vanish for symmetry reasons? 
    !   
    ! Input:
    !   sx,sy,sz: the signs under symmetry operation in each direction
    !   quantisation_axis: the axis with respect to which the angle theta is
    !                     defined. 1=X, 2=Y, 3=Z
    !   secondary_axis: the axis with respect to which the angle phi is defined.
    !                  1=X, 2=Y, 3=Z
    ! Output:
    !  moment_list: a 3D array that contains the information about which
    !               multipole moments are restricted by symmetry (0) and which 
    !               should be calculated (1).
    !- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ! We fill the list that decides which multipole moments are restricted by
    ! symmetry and which should be calculated. 
    !
    !  moment_list(l,m,k) = 0 => restricted by symmetry, 
    !              | | |           should not be calculated
    !              | | |
    !  moment_list(l,m,k) = 1 => should be calculated
    !              | | |
    !              | | -> k : real (0) or imaginary(1) part
    !              | ---> m : second characteristic number
    !              -----> l : first characteristic number
    !----------------------------------------------------------------------------
    integer, intent(in)  :: sx,sy,sz, maxmoment,quantisation_axis, secondary_axis
    integer              :: moment_list(0:maxmoment,0:maxmoment,0:1)

    real(KIND=dp)       :: test_coord_x(2), test_coord_y(2), test_coord_z(2)
    real(KIND=dp)       :: test_spher_harm(2,2,2,0:MaxMoment,0:MaxMoment,2)
    integer             :: l, m, impart, signx, signy, signz

    ! Testing mesh: two points in each direction, covering every octant of
    ! the simulation volume.
    test_coord_x = (/-1.0_dp,1.0_dp/) ! Although the precise testing coordinates  
    test_coord_y = (/-2.0_dp,2.0_dp/) ! do not matter, it is important to not be 
    test_coord_z = (/-3.0_dp,3.0_dp/) ! too close to zeros of spherical harmonics for numerical precision!

    ! Generate the spherical harmonics for the test coordinates
    call generate_spherical_harmonics(maxmoment, 2, 2, 2, &
    &     test_coord_x, test_coord_y, test_coord_z,       &
    &     test_spher_harm, quantisation_axis, secondary_axis)

    ! Allocate the moment_list array
    moment_list = 0 ! Initialise to zero

    ! Loop over the spherical harmonics and determine which ones will result in vanishing 
    ! expectation values for objects with symmetry properties sx/sy/sz.
    do impart=1,2
      do l = 0,maxmoment
        do m = 0, l

          if( m .eq. 0 .and. impart .eq. 2 ) cycle ! Imaginary part of m=0 is always zero, but the tests below might not catch this!

          ! The signs under reflection of the spherical harmonic for each cartesian direction
          signx = int(SIGN(1.0_dp, test_spher_harm(2,2,2,l,m,impart) / test_spher_harm(1,2,2,l,m,impart)))
          signy = int(SIGN(1.0_dp, test_spher_harm(2,2,2,l,m,impart) / test_spher_harm(2,1,2,l,m,impart)))
          signz = int(SIGN(1.0_dp, test_spher_harm(2,2,2,l,m,impart) / test_spher_harm(2,2,1,l,m,impart)))

          if((signx * sx < 0) .or. (signy * sy < 0) .or. (signz * sz < 0)) then
            ! \int d^3r f Y_{lm}(\theta,\phi) will vanish because of symmetry properties
            moment_list(l,m,impart-1) = 0
          else
            ! \int d^3r f Y_{lm}(\theta,\phi) will not vanish!
            moment_list(l,m,impart-1) = 1
          end if
          !if(moment_list(l,m,impart-1) .eq. 1) print *, l, m, impart-1, signx, signy, signz, sx, sy, sz, moment_list(l,m,impart-1) ! debug output
        enddo
      enddo
    enddo
   end function figure_out_multipole_moments
   
   subroutine generate_spherical_harmonics(maxmoment,mx,my,mz,                 &
   &                                xcoord,ycoord,zcoord,SpherHarmMesh,        &
   &                                quantisationaxis,secondaryaxis)
    !---------------------------------------------------------------------------
    ! This function computes the values of all the spherical harmonics up to
    ! l=Maxmoment where Mesh supplies the values of the x/y/z coordinates.
    
    ! The formula used is the one from Messiah:
    !    Y^{m}_{l} = (-1)^m [(2*l+1)/(4*\pi) (l-m)!/(l+m)!]^{1/2}
    !              *  P^m_{l}[cos(\theta)] e^{im\phi}
    !
    ! Translating this formula into Cartesian coordinates is highly dependent on
    ! the choices made for the correspondence between (x,y,z) and (r,\theta,\phi)
    ! spherical coordinates. This is why this routine has two parameters, 
    ! QuantisationAxis and SecondaryAxis, which determine the correspondence.
    ! 
    ! On output, SpherHarmMesh contains the values of the spherical harmonics
    ! at the mesh points. 
    ! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    ! Input: 
    !   maxmoment: the maximum value of l for which the spherical harmonics
    !              are computed
    !   mx,my,mz: the number of points in the x,y,z directions
    !   xcoord,ycoord,zcoord: the x,y,z coordinates of the mesh points
    !   quantisationaxis: the axis with respect to which the angle theta is
    !                     defined. 1=X, 2=Y, 3=Z
    !   secondaryaxis: the axis with respect to which the angle phi is defined.
    !                  1=X, 2=Y, 3=Z
    ! Output:
    !   SpherHarmMesh: the output array containing the values of the spherical 
    !                  harmonics on the mesh points
    !
    !---------------------------------------------------------------------------

    integer, intent(in)        :: mx,my,mz, maxmoment
    integer, intent(in)        :: quantisationaxis,secondaryaxis
    real(KIND=dp), intent(in)  :: xcoord(mx), ycoord(my), zcoord(mz)
    real(KIND=dp), intent(out) :: SpherHarmMesh(mx,my,mz,0:MaxMoment,0:MaxMoment,2)

    real(KIND=dp)  :: LegendreMesh (mx,my,mz,0:MaxMoment,0:MaxMoment)
    !r, Sin(\theta),Cos(\theta),\phi, sin(m*\Phi) and cos(m*\Phi)
    real(KIND=dp)  :: r,cosTheta,sinTheta, phi,sinmPhi, cosmPhi
    real(KIND=dp)  :: fac, X,Y,Z
    integer        :: i,j,k,l,m,q
    real(KIND=dp)  :: factorialquotient

    do k=1,mz
      do j=1,my
        do i=1,mx
          X = xcoord(i)
          Y = ycoord(j)
          Z = zcoord(k)

          r        =sqrt(X**2+Y**2+Z**2)
          phi      =0
          select case(QuantisationAxis)
          case(1)
                ! QuantisationAxis = X
                ! Meaning the angle theta is with reference to X-direction
                sinTheta =sqrt(Z**2+Y**2)/r
                cosTheta =X/r

                select case(SecondaryAxis)
                case(1)
                  phi      =atan2(Z,Y)
                case(2)
                  phi      =atan2(Y,Z)
                end select
          case(2)
                ! QuantisationAxis = Y
                ! Meaning the angle theta is with reference to Y-direction
                sinTheta =sqrt(X**2+Z**2)/r
                cosTheta =Y/r

                select case(SecondaryAxis)
                case(1)
                  phi      =atan2(Z,X)
                case(2)
                  phi      =atan2(X,Z)
                end select
          case(3)
                ! QuantisationAxis = Z
                ! Meaning the angle theta is with reference to Z-direction
                sinTheta =sqrt(X**2+Y**2)/r
                cosTheta =Z/r

                select case(SecondaryAxis)
                case(1)
                  phi      =atan2(Y,X)
                case(2)
                  phi      =atan2(X,Y)
                end select
          case DEFAULT
            call stp('Quantisationaxis is not valid in GenSphericalHarmonics.')
          end select

          !Calculating the values of the spherical harmonics
          do m=0,MaxMoment
            ! Finding the associated Legendre Polynomials
            LegendreMesh(i,j,k,:,m)=legendre_pnm(MaxMoment, m, cosTheta)
            sinmPhi=sin(m*Phi)
            cosmPhi=cos(m*Phi)

            do l=m,MaxMoment ! Note that l>= m
              factorialquotient=1.0_dp
              do q=1,2*m
                factorialquotient = factorialquotient/( l + m - q + 1)
              enddo

              fac=(-1)**m*sqrt(factorialquotient)*r**l
              fac = fac * sqrt((2*l +1)/(4 * pi))
              ! Real part of Y_{lm}
              SpherHarmMesh(i,j,k,l,m,1)=fac*LegendreMesh(i,j,k,l,m)*cosmPhi
              ! Imaginary part of Y_{lm}
              SpherHarmMesh(i,j,k,l,m,2)=fac*LegendreMesh(i,j,k,l,m)*sinmPhi
            enddo
          enddo
        enddo
      enddo
    enddo

 end subroutine generate_spherical_harmonics

 function legendre_pnm ( n, m, x ) result(cx)
      !-------------------------------------------------------------------------
      ! Taken on 14/05/13 from
      !    http://people.sc.fsu.edu/~jburkardt/f_src/polpak/polpak.html
      ! Under the GNU LGPL licence, which can be found at
      !    http://www.gnu.org/licenses/gpl.html
      !
      ! Minor changes from the original version:
      !    - double precision instead of single precision
      !    - changed from subroutine to function, for clarity and ease of use
      !*************************************************************************
      !
      ! LEGENDRE_PNM evaluates the associated Legendre polynomial Pnm(x) of the 
      !first kind.
      !
      !
      !  Differential equation:
      !
      !    (1-X*X) * Y'' - 2 * X * Y + ( N (N+1) - (M*M/(1-X*X)) * Y = 0
      !
      !  First terms:
      !
      !    M = 0  ( = Legendre polynomials of first kind P(N)(X) )
      !
      !    P00 =    1
      !    P10 =    1 X
      !    P20 = (  3 X**2 -   1)/2
      !    P30 = (  5 X**3 -   3 X)/2
      !    P40 = ( 35 X**4 -  30 X**2 +   3)/8
      !    P50 = ( 63 X**5 -  70 X**3 +  15 X)/8
      !    P60 = (231 X**6 - 315 X**4 + 105 X**2 -  5)/16
      !    P70 = (429 X**7 - 693 X**5 + 315 X**3 - 35 X)/16
      !
      !    M = 1
      !
      !    P01 =   0
      !    P11 =   1 * SQRT(1-X*X)
      !    P21 =   3 * SQRT(1-X*X) * X
      !    P31 = 1.5 * SQRT(1-X*X) * (5*X*X-1)
      !    P41 = 2.5 * SQRT(1-X*X) * (7*X*X*X-3*X)
      !
      !    M = 2
      !
      !    P02 =   0
      !    P12 =   0
      !    P22 =   3 * (1-X*X)
      !    P32 =  15 * (1-X*X) * X
      !    P42 = 7.5 * (1-X*X) * (7*X*X-1)
      !
      !    M = 3
      !
      !    P03 =   0
      !    P13 =   0
      !    P23 =   0
      !    P33 =  15 * (1-X*X)**1.5
      !    P43 = 105 * (1-X*X)**1.5 * X
      !
      !    M = 4
      !
      !    P04 =   0
      !    P14 =   0
      !    P24 =   0
      !    P34 =   0
      !    P44 = 105 * (1-X*X)**2
      !
      !  Recursion:
      !
      !    if N < M:
      !      P(N,M) = 0
      !    if N = M:
      !      P(N,M) = (2*M-1)!! * (1-X*X)**(M/2) where N!! means the product of
      !      all the odd integers less than or equal to N.
      !    if N = M+1:
      !      P(N,M) = X*(2*M+1)*P(M,M)
      !    if N > M+1:
      !      P(N,M) = ( X*(2*N-1)*P(N-1,M) - (N+M-1)*P(N-2,M) )/(N-M)
      !
      !  Restrictions:
      !
      !    -1 <= X <= 1
      !     0 <= M <= N
      !
      !  Special values:
      !
      !    P(N,0)(X) = P(N)(X), that is, for M=0, the associated Legendre
      !    polynomial of the first kind equals the Legendre polynomial of the
      !    first kind.
      !
      !  Modified:
      !
      !    24 June 2001
      !
      !  Author:
      !
      !    John Burkardt
      !
      !  Parameters:
      !
      !    Input, integer N, the maximum first index of the Legendre
      !    polynomial, which must be at least 0.
      !
      !    Input, integer M, the second index of the Legendre polynomial,
      !    which must be at least 0, and no greater than N.
      !
      !    Input, real X, the point at which the polynomial is to be
      !    evaluated.  X must satisfy -1 <= X <= 1.
      !
      !    Output, real CX(0:N), the values of the first N+1 polynomials.
      !-------------------------------------------------------------------------
      implicit none

      real(KIND=dp)    :: cx(0:n)
      real(KIND=dp)     :: fact, somx2
      real(KIND=dp),  intent(in) :: x
      integer, intent(in) :: m,n
      integer :: i

      if ( m < 0 ) then
      write ( *, '(a)' ) ' '
      write ( *, '(a)' ) 'LEGENDRE_PNM - Fatal error!'
      write ( *, '(a,i6)' ) '  Input value of M is ', m
      write ( *, '(a)' ) '  but M must be nonnegative.'
      stop
      end if

      if ( m > n ) then
      write ( *, '(a)' ) ' '
      write ( *, '(a)' ) 'LEGENDRE_PNM - Fatal error!'
      write ( *, '(a,i6)' ) '  Input value of M = ', m
      write ( *, '(a,i6)' ) '  Input value of N = ', n
      write ( *, '(a)' ) '  but M must be less than or equal to N.'
      stop
      end if

      if ( x < -1.0E+00 ) then
      write ( *, '(a)' ) ' '
      write ( *, '(a)' ) 'LEGENDRE_PNM - Fatal error!'
      write ( *, '(a,g14.6)' ) '  Input value of X = ', x
      write ( *, '(a)' ) '  but X must be no less than -1.'
      stop
      end if

      if ( x > 1.0E+00 ) then
      write ( *, '(a)' ) ' '
      write ( *, '(a)' ) 'LEGENDRE_PNM - Fatal error!'
      write ( *, '(a,g14.6)' ) '  Input value of X = ', x
      write ( *, '(a)' ) '  but X must be no more than 1.'
      stop
      end if

      cx(0:m-1) = 0.0E+00

      cx(m) = 1.0E+00
      somx2 = sqrt ( 1.0E+00 - x**2 )

      fact = 1.0E+00
      do i = 1, m
          cx(m) = - cx(m) * fact * somx2
          fact = fact + 2.0E+00
      end do

      if ( m == n ) then
          return
      end if

      cx(m+1) = x * real ( 2 * m + 1 ) * cx(m)

      do i = m+2, n
          cx(i) = ( real ( 2 * i - 1 ) * x * cx(i-1) &
          - real ( i + m - 1 ) * cx(i-2) ) / real ( i - m )
      end do

      return
  end function Legendre_pnm


end module sphericalharmonics
