#-------------------------------------------------------------------------------
# CI/CD deployment for MOCCa on github
#
# The logic of this workflow is simple:
# - the compile job creates all possible combinations of executables
# - ... and the following jobs run all defined tests using these executables.
#
# It is currently only verified to run on one or more of the astropc computers.
#
#-------------------------------------------------------------------------------
name: Tantalus CI/CD Workflow
#TODO:
# [ ] reenable tests with HFB for the master branch
on:
  push:
    branches:
      - master
      - difficult_merge
  pull_request:
    branches:
      - master
      - difficult_merge
jobs:
  compile:
    #------------------------------------------------------------------------------
    # Compile many different executables for different
    #   - CONFIG   = configuration file
    #   - COMPILER = different compiler
    #   - CALCTYPE = nuclei or pasta
    #------------------------------------------------------------------------------
    runs-on: self-hosted
    strategy:
      matrix:
        CONFIG     :   [ NLO, BXL,BXL-T,BXL-P,BXL-TP, N2LO,N2LO-T, N2LO-P,N2LO-TP ]
        COMPILER   :   [ gfortran   ]
        CALCTYPE   :   [ NUCLEI     ]
        include :
            # Only check pasta with BXL configuration
            - CALCTYPE: PASTA
              CONFIG  : BXL
              COMPILER: gfortran
            - CALCTYPE: PASTA
              CONFIG  : BXL
              COMPILER: ifx
            # Compile a few things with ifort to have a compiler independence check
            - CALCTYPE: NUCLEI
              CONFIG  : NLO
              COMPILER: ifx
            - CALCTYPE: NUCLEI
              CONFIG  : BXL
              COMPILER: ifx
    env:
      # Uniquely labelling the executables with this environment variable
      SUFFIX: ${{ matrix.CONFIG }}.${{ matrix.COMPILER }}.${{ matrix.CALCTYPE }}
      # Compiler family
      COMPFAM:  ${{ matrix.COMPILER == 'gfortran' && 'gnu' || 'intel' }}

      # There is not yet any intel HDF5 on astropc19, but enable it 
      #   by default for gfortran
      HDF5SUFFIX: ${{ matrix.COMPILER == 'gfortran' && '-hdf5'|| '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare src directory
        # ---------------------------------------------------------------------------
        # This is a horrible hack:
        #   unfortunately the current Makefile configuration of Tantalus will always
        #   fail the first time around because Hephaestos has not created f90 files
        #   in the src/ directory yet. I have not found a way to correctly do this
        #   dependency in the Makefile yet...;
        # ---------------------------------------------------------------------------
        run: |
            mkdir src/
            cp src_orig/*.f90 src
      # - name: Compile Tantalus
      #   if: ${{ contains(github.ref, "master") }}
      #   # The setvars.sh ensures that the intel compilers are available on the astropcs
      #   run: |
      #     source /opt/intel/oneapi/setvars.sh --force &> /dev/null
      #     make CONFIG=${{ matrix.CONFIG }} COMPILER=${{ matrix.COMPILER }} EXENAME=Tantalus.${{ matrix.CONFIG }}.${{ matrix.COMPILER }}.${{ matrix.CALCTYPE }}.exe CALCTYPE=${{ matrix.CALCTYPE }}
      - name: Compile Tantalus
        # 1. The setvars.sh ensures that the intel compilers are available on the astropcs
        # 2. The copy command ensures the right compilation options
        run: |
          source /opt/intel/oneapi/setvars.sh --force &> /dev/null
          cp make_include/make.inc.${{ env.COMPFAM }}-serial${{ env.HDF5SUFFIX }} make.inc
          make CONFIG=${{ matrix.CONFIG }} EXENAME=Tantalus.${{ env.SUFFIX }}.exe CALCTYPE=${{ matrix.CALCTYPE }}

      - name: Upload compilation artifact
        # Upload the executable such that next steps can download them!
        uses: actions/upload-artifact@v4
        with:
          name: exec-${{ env.SUFFIX }}
          path: exec/Tantalus.${{ env.SUFFIX }}.exe
          retention-days: 2
  minimal:
    #-----------------------------------------------------------------------------
    # Run the 'minimal' test for two different compilers.
    #-----------------------------------------------------------------------------
    runs-on: self-hosted
    needs:   compile
    strategy:
      matrix:
        COMPILER: [gfortran, ifx]
    env:
      SUFFIX: NLO.${{ matrix.COMPILER }}.NUCLEI
    steps:
      - uses: actions/download-artifact@v4
        # Start by downloading the relevant executable
        with:
          name: exec-${{ env.SUFFIX }}
          path: exec/

      - name: Make executeable
        # Unfortunately, github artifacts don't retain permissions.
        run:  chmod +x exec/Tantalus.${{ env.SUFFIX }}.exe

      - name: Run minimal test
        # Perform the test
        run: |
          cd testing/integration/
          source /opt/intel/oneapi/setvars.sh --force &> /dev/null
          bash minimal.sh $SUFFIX

      - name: Upload test results
        # Upload the log files as artefact
        uses: actions/upload-artifact@v4
        with:
          name: minimal-${{ env.SUFFIX }}
          path: testing/integration/logs/minimal.${{ env.SUFFIX }}.out
          retention-days: 90
  boundary_conditions:
    #-----------------------------------------------------------------------------
    # Run the boundary conditions test
    #-----------------------------------------------------------------------------
    runs-on: self-hosted
    needs:   compile
    strategy:
      matrix:
        COMPILER:
          - ifx
    env:
      SUFFIX: BXL.${{ matrix.COMPILER }}
    steps:
      # Start by downloading the relevant executable
      - uses: actions/download-artifact@v4
        with:
          name: exec-${{ env.SUFFIX }}.NUCLEI
          path: exec/
      - uses: actions/download-artifact@v4
        with:
          name: exec-${{ env.SUFFIX }}.PASTA
          path: exec/

      - name: Make executeable
        # Unfortunately, github artifacts don't retain permissions.
        run: |
          chmod +x exec/Tantalus.${{ env.SUFFIX }}.NUCLEI.exe
          chmod +x exec/Tantalus.${{ env.SUFFIX }}.PASTA.exe

      - name: Run boundary conditions test
        # Perform the test
        run: |
          cd testing/integration/
          source /opt/intel/oneapi/setvars.sh --force &> /dev/null
          bash boundary_conditions.sh -p BSkG3_naked -e $SUFFIX.NUCLEI -f $SUFFIX.PASTA

      - name: Upload test results
        # Upload the log files as artefact
        uses: actions/upload-artifact@v4
        with:
          name: boundary_conditions-${{ env.SUFFIX }}
          path: |
            testing/integration/logs/minimal.${{ env.SUFFIX }}.NUCLEI.out
            testing/integration/logs/minimal.${{ env.SUFFIX }}.PASTA.out
          retention-days: 90
  store_derivatives:
    #-----------------------------------------------------------------------------
    # Run the 'store_derivatives' test
    #-----------------------------------------------------------------------------
    runs-on: self-hosted
    needs: compile
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        CONFIG  : [BXL,N2LO]
        COMPILER: [gfortran]
        CALCTYPE: [NUCLEI]
        include :
          - CONFIG: BXL
            PARAM : BSkG3
          - CONFIG: N2LO
            PARAM : SN2LO1
    env:
      # Uniquely labelling the executables with this environment variable
      SUFFIX: ${{ matrix.CONFIG }}.${{ matrix.COMPILER }}.${{ matrix.CALCTYPE }}
    steps:
      - uses: actions/download-artifact@v4
        # Download the executable
        with:
          name: exec-${{ env.SUFFIX }}
          path: exec/

      - name: Make executeable
        # Unfortunately, github artifacts don't retain permissions.
        run:  chmod +x exec/Tantalus.${{ env.SUFFIX }}.exe

      - name: Run store_derivatives test
        # Actually execute the test
        run: |
          cd testing/integration/
          bash store_derivatives.sh -p ${{ matrix.PARAM }} -e ${{ env.SUFFIX }}

      - name: Upload store_derivatives test results
        uses: actions/upload-artifact@v4
        with:
          name: store_derivatives-${{ matrix.PARAM }}-${{ matrix.CONFIG }}-${{ matrix.COMPILER }}
          path: |
            testing/integration/logs/store_derivatives=true.${{ env.SUFFIX }}.out
            testing/integration/logs/store_derivatives=false.${{ env.SUFFIX }}.out
          retention-days: 90

  lattice_energy:
    #---------------------------------------------------------------------------
    # Run the 'lattice-energy' test
    #---------------------------------------------------------------------------
    runs-on: self-hosted
    needs: compile
    if: github.ref == 'refs/heads/difficult_merge'
    strategy:
      matrix:
        COMPILER: [ gfortran ] 
        CONFIG:   [ BXL      ]
    env:
      # Uniquely labelling the executables with this environment variable
      SUFFIX_VAC: ${{ matrix.CONFIG }}.${{ matrix.COMPILER }}.NUCLEI
      SUFFIX_PAS: ${{ matrix.CONFIG }}.${{ matrix.COMPILER }}.PASTA

    steps:
      - uses: actions/download-artifact@v4
        # Download the executables
        with:
          name: exec-${{ env.SUFFIX_VAC }}
          path: exec/
      - uses: actions/download-artifact@v4
        # Download the executables
        with:
          name: exec-${{ env.SUFFIX_PAS }}
          path: exec/

      - name: Make executeable
        # Unfortunately, github artifacts don't retain permissions.
        run:  |
          chmod +x exec/Tantalus.${{ env.SUFFIX_VAC }}.exe
          chmod +x exec/Tantalus.${{ env.SUFFIX_PAS }}.exe

      - name: Run lattice energy test
        # Actually execute the test
        run: |
          cd testing/integration/
          bash lattice_energy.sh -p BSkG4simpl -e ${{ env.SUFFIX_VAC }} -f ${{ env.SUFFIX_PAS }} -n 12

      - name: Upload store_derivatives test results
        uses: actions/upload-artifact@v4
        with:
          name: lattice_energy
          path: |
            testing/integration/logs/lattice_energy.${{ env.SUFFIX_VAC }}.out
            testing/integration/logs/lattice_energy.${{ env.SUFFIX_PAS }}.out
          retention-days: 90

  spaghetti:
    #---------------------------------------------------------------------------
    # Run the 'spaghetti' test
    #---------------------------------------------------------------------------
    runs-on: self-hosted
    needs: compile
    if: github.ref == 'refs/heads/difficult_merge'
    strategy:
      matrix:
        COMPILER: [ gfortran ]
        CONFIG:   [ BXL      ]
    env:
      # Uniquely labelling the executables with this environment variable
      SUFFIX: ${{ matrix.CONFIG }}.${{ matrix.COMPILER }}.PASTA
    steps:
      - uses: actions/download-artifact@v4
        # Download the executables
        with:
          name: exec-${{ env.SUFFIX }}
          path: exec/

      - name: Make executeable
        # Unfortunately, github artifacts don't retain permissions.
        run:  |
          chmod +x exec/Tantalus.${{ env.SUFFIX }}.exe

      - name: Run spaghetti test
        # Actually execute the test
        run: |
          cd testing/integration/
          bash spagh.sh ${{ env.SUFFIX }}

      - name: Upload store_derivatives test results
        uses: actions/upload-artifact@v4
        with:
          name: spaghetti
          path: |
            testing/integration/logs/lattice_energy.${{ env.SUFFIX }}.out
          retention-days: 90


  symmetries:
    #-----------------------------------------------------------------------------
    # Run the 'symmetries' test
    #-----------------------------------------------------------------------------
    runs-on: self-hosted
    needs: compile
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        CONFIG  : [BXL, N2LO]
        COMPILER: [ gfortran]
        CALCTYPE: [ NUCLEI  ]
        include :
          - CONFIG: BXL
            PARAM : BSkG3
          - CONFIG: N2LO
            PARAM : SN2LO1

    env:
       EXEC    : ${{ matrix.CONFIG }}.${{ matrix.COMPILER }}.${{ matrix.CALCTYPE }}
       EXEC_P  : ${{ matrix.CONFIG }}-P.${{ matrix.COMPILER }}.${{ matrix.CALCTYPE }}
       EXEC_T  : ${{ matrix.CONFIG }}-T.${{ matrix.COMPILER }}.${{ matrix.CALCTYPE }}
       EXEC_TP : ${{ matrix.CONFIG }}-TP.${{ matrix.COMPILER }}.${{ matrix.CALCTYPE }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: exec-${{ env.EXEC }}
          path: exec/
      - uses: actions/download-artifact@v4
        with:
          name: exec-${{ env.EXEC_P }}
          path: exec/
      - uses: actions/download-artifact@v4
        with:
          name: exec-${{ env.EXEC_T }}
          path: exec/
      - uses: actions/download-artifact@v4
        with:
          name: exec-${{ env.EXEC_TP }}
          path: exec/

      - name: Make executeable
        run:  |
         chmod +x exec/Tantalus.${{ env.EXEC    }}.exe
         chmod +x exec/Tantalus.${{ env.EXEC_P  }}.exe
         chmod +x exec/Tantalus.${{ env.EXEC_T  }}.exe
         chmod +x exec/Tantalus.${{ env.EXEC_TP }}.exe

      - name: Run symmetries test
        # Useage: bash symmetries param exec exec_P exec_T exec_TP
        run: |
          cd testing/integration/
          bash symmetries.sh ${{ matrix.param }} ${{ env.EXEC }} ${{ env.EXEC_P }} ${{ env.EXEC_T }} ${{ env.EXEC_TP }}

      - name: Upload symmetries test results
        uses: actions/upload-artifact@v4
        with:
          name: symmetries-test-results-${{ matrix.PARAM }}-${{ matrix.CONFIG }}-${{ matrix.COMPILER }}
          path: |
            testing/integration/logs/symmetries.${{ env.EXEC    }}.out
            testing/integration/logs/symmetries.${{ env.EXEC_T  }}.out
            testing/integration/logs/symmetries.${{ env.EXEC_P  }}.out
            testing/integration/logs/symmetries.${{ env.EXEC_TP }}.out
          retention-days: 90

